MobiVM/robovm

compiler/compiler/src/test/resources/org/robovm/compiler/config/ConfigTest.console.xml
compiler/compiler/src/test/resources/org/robovm/compiler/config/ConfigTest.ios.xml

[Related issue ](https://github.com/MobiDevelop/robovm/issues/5)

Adjusting Config tests so the build completes

---

plugins/eclipse/ui/pom.xml

Otherwise eclipse plugin can't be compiled.

Change version of parent pom.xml

---

plugins/idea/src/main/java/org/robovm/idea/actions/CreateIpaDialog.java

Architecture selection fix.

---

plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java

PR 110 had broken Idea plugin in non development mode. This PR to fix it back

fixes to PR110 

---

compiler/cocoatouch/src/main/bro-gen/gamekit.yaml
compiler/cocoatouch/src/main/java/org/robovm/apple/gamekit/GKPlayer.java

Avoids non ios 10 issues as GKBasePlayer is ios10 only.

Break inheritance chain with GKPlayer and GKBasePlayer

---

compiler/compiler/src/main/java/org/robovm/compiler/Annotations.java
compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCBlockPlugin.java
compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/TypeEncoder.java
compiler/objc/src/main/java/org/robovm/objc/ObjCBlock.java
compiler/objc/src/main/java/org/robovm/objc/RunnableAsObjCBlockMarshaler.java

also fixes https://github.com/MobiDevelop/robovm/issues/121

blocks implementation -- added signature generation to blocks

---

compiler/compiler/src/main/resources/Entitlements.plist

https://github.com/MobiDevelop/robovm/issues/168

fix of issue #168

---

compiler/compiler/src/main/java/org/robovm/compiler/DependencyGraph.java

We have a pretty mammoth project (~150k methods), and when building IPA's I was running into a StackOverflowException inside `DependencyGraph`. I've reworked it to avoid the recursion.
Confirmed `DependencyGraphTest` passes, and our IPA is now building. Thanks!

Removed the recursion from DependencyGraph#visitReachableNodes

---

compiler/compiler/src/main/java/org/robovm/compiler/AppCompiler.java
compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java
compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java
compiler/compiler/src/main/java/org/robovm/compiler/target/Target.java
compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompileTask.java

prepareForLaunch moved to compile phase. reason for this is that previous place of IOSTarget.doLaunch is bad as it was calling from IDEA thread which causes it to become unresponsive for some time (30 sec in my case)
similar issue is described here http://badlogicgames.com/forum/viewtopic.php?f=11&t=26347

unfreezes IDEA during prepareForLaunch

---

plugins/eclipse/ui/META-INF/MANIFEST.MF
plugins/eclipse/ui/plugin.xml
plugins/eclipse/ui/pom.xml
plugins/eclipse/ui/src/org/robovm/eclipse/internal/ib/IBIntegratorManager.java
plugins/eclipse/ui/src/org/robovm/eclipse/internal/ib/IBIntegratorProxy.java
plugins/eclipse/ui/src/org/robovm/eclipse/internal/ib/OpenXcodeAction.java

integrated IB/XCode to eclipse as well, removed broken "new story board" etc wizards

Ib eclipse

---

compiler/objc/src/main/java/org/robovm/objc/ObjCClass.java

to allow Native side to check them with conformsToProtocol call 
(GMSMapView.setDelegate issue)

added registration of protocols to custom classes 

---

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SDK.java
compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java
compiler/compiler/src/test/java/org/robovm/compiler/target/ios/SDKTest.java

Fix for #202 
Clean version of old PR (#203)

Make manually installed simulator runtimes available to Robovm

---

plugins/eclipse/ui/build.properties

release build of eclipse plugin was not working due bcel library was not packed

BCEL library was not packed into release plugin jar 

---

compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java

+ optimized: copy only if required, strip in one round

fixed #228

---

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCMemberPlugin.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/Utils.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/consts/ClassNames.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/export/IBOutletExportMemberItem.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassHierarchyData.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassHierarchyResolver.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassMemberParser.java

plugging extended to understand limited set of structs
compiler fixed to add @ByVal annotation for generated IBOutlet/IBInspectable setters
long read: https://dkimitsa.github.io/2017/11/03/fix230-interface-builder-and-struct-outlets/

fixed #230: IB

---

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCMemberPlugin.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/Utils.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/consts/ClassNames.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/export/IBOutletExportMemberItem.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassHierarchyData.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassHierarchyResolver.java
plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassMemberParser.java

previous PR exposed quite old bug

Fix 230, extra bug found (IB @CustomClass was broken by previous PR)

---

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SDK.java
plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.java
plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunConfiguration.java
plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunProfileState.java

fixed 262: Idea,simulator configuration is now being picked not only by name but by version

---

plugins/templates/ios-framework/src/main/resources/archetype-resources/headers/__appName__.h
plugins/templates/ios-framework/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/Api.java
plugins/templates/ios-framework/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/__mainClass__Impl.java

otherwise any crash reporter will cause random application crashes

Framework project template updated with API to Signals.installSignal

---

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SigningIdentity.java

distribution identities shall be ignored for run configurations

* fixed auto-identity pick-up (auto for identity, auto for profile)

---

compiler/rt/libcore/luni/src/main/java/java/text/DecimalFormatSymbols.java
plugins/debugger/src/main/java/org/robovm/debugger/delegates/JdwpEventCenterDelegate.java
plugins/debugger/src/main/java/org/robovm/debugger/jdwp/handlers/vm/JdwpVmCapabilitiesNewHandler.java
plugins/debugger/src/main/java/org/robovm/debugger/state/VmSpecConsts.java
plugins/eclipse/ui/pom.xml

first commit fixes the issue 
second just fixes spelling from previous PR review  (just to reduce amount of PRs)

Fix #309 and JDWP version downgrade to 1.5

---

compiler/cocoatouch/src/main/java/org/robovm/apple/arkit/ARFaceGeometry.java
compiler/cocoatouch/src/main/java/org/robovm/apple/arkit/ARPlaneGeometry.java
compiler/cocoatouch/src/main/java/org/robovm/apple/arkit/ARPointCloud.java
compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKPath.java
compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKPolygonObstacle.java
compiler/cocoatouch/src/main/java/org/robovm/apple/metalps/MPSCNNConvolutionDataSource.java
compiler/cocoatouch/src/main/java/org/robovm/apple/metalps/MPSCNNConvolutionDataSourceAdapter.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLAnimatedMatrix4x4.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLAnimatedQuaternionArray.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLAnimatedVector2.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLAnimatedVector3.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLAnimatedVector3Array.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLAnimatedVector4.java
compiler/cocoatouch/src/main/java/org/robovm/apple/modelio/MDLMatrix4x4Array.java
compiler/cocoatouch/src/main/java/org/robovm/apple/spritekit/SKWarpGeometryGrid.java

Problem were cause by bug in bro-gen that was not recognize manually defined structs (which are vector structs in foundation.yaml) as structs and generated wrong types for it.
upd. [bro-gen fix](https://github.com/dkimitsa/robovm-bro-gen/commit/0c20d00ac6a7f49fccea8b4c1b37458547b958a0)

fix for pointer to vector structs bindings 

---

compiler/compiler/src/main/java/org/robovm/compiler/clazz/Java9RuntimePath.java

fixed different behaviour of resolving list of Java9+ modules in jrt file system between Oracle JDK and OpenJDK.
On OpenJDK (v13 was tested) when getting path using `Paths.get(URI.create("jrt:/modules"))` its returns it as /modules/modules as result fails to resolve.
It resolves list of modules when using "jrt:/" uri, but it doesn't work if "jrt:/modules" was used before "jrt:/". E.g. this part is heavily broken
Same fix will go to Soot later (but it is not critical)

* fixed resolving list of Java9+ modules in OpenJDK

---

dist/compiler/pom.xml
plugins/debugger/pom.xml
plugins/eclipse/pom.xml
plugins/ibxcode/pom.xml
plugins/maven/pom.xml
pom.xml

recent Tycho dependency enable compilation of eclipse plugin with recent JDK12/13

Jdk12 wip/eclipse tycho 1.5

---

compiler/cocoatouch/src/main/java/org/robovm/apple/glkit/GLKMatrix3.java
compiler/cocoatouch/src/main/java/org/robovm/apple/glkit/GLKMatrix4.java
compiler/cocoatouch/src/main/java/org/robovm/apple/glkit/GLKQuaternion.java
compiler/cocoatouch/src/main/java/org/robovm/apple/glkit/GLKVector3.java
compiler/cocoatouch/src/main/java/org/robovm/apple/glkit/GLKVector4.java
compiler/vm/build.sh
plugins/eclipse/feature/feature.xml
plugins/eclipse/feature/pom.xml
plugins/eclipse/pom.xml
plugins/eclipse/update-site/pom.xml
plugins/eclipse/update-site/site.xml
plugins/idea/README.md

- fixed blocking GLKVector3 create issue 
- reverted back missing eclipse site-update modules 
- updated Idea readme for setting up maven development copy
- ~VM build script tweaked to use 6 process instead of one~ reverted as was failing and delivered as #451

2.3.10 hotfix1

---

compiler/compiler/src/main/java/org/robovm/compiler/target/framework/FrameworkTarget.java
compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java

same as  #463 into jdk12, to sync with master
* Fixes min OS version checks and removes hardcoded values

Fixes min OS version (#463 into jdk12)

---

compiler/cocoatouch/src/main/bro-gen/automaticassessmentconfiguration.yaml
compiler/cocoatouch/src/main/bro-gen/mapkit.yaml
compiler/cocoatouch/src/main/bro-gen/passkit.yaml
compiler/cocoatouch/src/main/java/org/robovm/apple/automaticac/AEAssessmentConfiguration.java
compiler/cocoatouch/src/main/java/org/robovm/apple/automaticac/AEAssessmentErrorCode.java
compiler/cocoatouch/src/main/java/org/robovm/apple/automaticac/AEAssessmentSession.java
compiler/cocoatouch/src/main/java/org/robovm/apple/automaticac/AEAssessmentSessionDelegate.java
compiler/cocoatouch/src/main/java/org/robovm/apple/automaticac/AEAssessmentSessionDelegateAdapter.java
compiler/cocoatouch/src/main/java/org/robovm/apple/coregraphics/CGColorSpace.java
compiler/cocoatouch/src/main/java/org/robovm/apple/gamekit/GKLocalPlayer.java
compiler/cocoatouch/src/main/java/org/robovm/apple/healthkit/HKSampleType.java
compiler/cocoatouch/src/main/java/org/robovm/apple/imageio/CGImagePropertyExif.java
compiler/cocoatouch/src/main/java/org/robovm/apple/intentsui/INUIAddVoiceShortcutButton.java
compiler/cocoatouch/src/main/java/org/robovm/apple/intentsui/INUIAddVoiceShortcutViewController.java
compiler/cocoatouch/src/main/java/org/robovm/apple/intentsui/INUIEditVoiceShortcutViewController.java
compiler/cocoatouch/src/main/java/org/robovm/apple/mapkit/MKMapItem.java
compiler/cocoatouch/src/main/java/org/robovm/apple/networkextension/NEFilterDataProvider.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKAddSecureElementPassErrorCode.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKPass.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKPassLibrary.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKPassType.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKPaymentMethod.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKPaymentPassActivationState.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKSecureElementPass.java
compiler/cocoatouch/src/main/java/org/robovm/apple/passkit/PKSecureElementPassActivationState.java
compiler/cocoatouch/src/main/java/org/robovm/apple/photos/PHLivePhotoRequestOptions.java
compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UIKeyCommand.java
compiler/cocoatouch/src/main/java/org/robovm/apple/webkit/WKWebView.java

reflects changes in recent [beta3](http://codeworkshop.net/objc-diff/sdkdiffs/ios/13.4b3/). 
also full re-gen was run that picked up few moments.

binding ios13.4. update to Xcode11.4 beta3

---

compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java

workaround to support static libraries that use swift libraries:
- to find you what libraries you lib depends on use `otool -l libOne.a | grep "\-lswift"`
- list all swift dependencies in robovm in `libs` section similar to bellow:
```
<libs>
<lib>libswiftCore.dylib</lib>
</libs>
```

support for static libs with swift usage

---

plugins/idea/build.gradle
plugins/idea/src/main/java/org/robovm/idea/components/RoboVmBuildProcessParametersProvider.java
plugins/idea/src/main/java/org/robovm/idea/gradle/RoboVMGradleProjectResolver.java
plugins/idea/src/main/java/org/robovm/idea/ibxcode/RoboVmIbXcodeProjectTask.java
plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunConfiguration.java
plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunner.java
plugins/idea/src/main/resources/META-INF/plugin.xml

Code adapted to match changes in idea 2020.1
Also minimal supported version of idea set to 2019.1

Idea plugin -- changes to match Idea 2020.1

---

compiler/cocoatouch/src/main/bro-gen/corenfc.yaml
compiler/cocoatouch/src/main/java/org/robovm/apple/corenfc/NFCTag.java
compiler/cocoatouch/src/main/java/org/robovm/apple/corenfc/NFCTagReaderSessionDelegateAdapter.java
compiler/cocoatouch/src/main/java/org/robovm/apple/corenfc/NSUserActivityExtensions.java

* added marshaller to didDetectTags to correctly marshal into protocol proxy
* added missing category
* fixed method naming

corenfc: added custom marshaller to didDetectTags

---

compiler/cocoatouch/src/main/bro-gen/exposurenotification.yaml
compiler/cocoatouch/src/main/bro-gen/healthkit.yaml
compiler/cocoatouch/src/main/java/org/robovm/apple/coregraphics/CGColorSpace.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENAttenuation.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENAuthorizationStatus.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENCalibrationConfidence.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENDiagnosisReportType.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENErrorCode.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENExposureConfiguration.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENExposureDetectionSummary.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENExposureFlags.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENExposureInfo.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENInfectiousness.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENManager.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENRiskLevel.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENRiskLevelValue.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENRiskScore.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENRiskWeight.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENStatus.java
compiler/cocoatouch/src/main/java/org/robovm/apple/exposurenotification/ENTemporaryExposureKey.java
compiler/cocoatouch/src/main/java/org/robovm/apple/healthkit/HKCategoryTypeIdentifier.java
compiler/cocoatouch/src/main/java/org/robovm/apple/healthkit/HKCategoryValueAppetiteChanges.java
compiler/cocoatouch/src/main/java/org/robovm/apple/healthkit/HKCategoryValuePresence.java
compiler/cocoatouch/src/main/java/org/robovm/apple/healthkit/HKCategoryValueSeverity.java

* updated to ios13.5, new framework ExposureNotification

ios13.5, 13.6 bindings

---

compiler/compiler/src/main/java/org/robovm/compiler/plugin/debug/DebuggerLaunchPlugin.java

Root case: wrong application path was set for console target when running under debugger.

* Fixed: console target failed to run under debugger.

---

plugins/idea/README.md
plugins/idea/src/main/resources/META-INF/com.mobidevelop.robovm.intellij-maven.xml
plugins/idea/src/main/resources/META-INF/plugin.xml

(config file was required for optional maven plugin -- added empty)

* Fixed: Idea 2021.2 compatibility 

---

compiler/rt/libcore/libdvm/src/main/java/java/lang/Daemons.java

on minimize iOS will put application to background and suspend all threads.
if background time is longer than MAX_FINALIZE_NANOS and watchdog was
waiting on object -- sleep will exit before finalizer and will cause
`$classname`.finalize() timed out after 10 seconds
split wait interval into two. This will allow to survive this case

* fixed: TimeoutException $classname.finalize() timed out after 10 seconds

---

README.md

Updating an old link to the new webpage.

Update homepage link  in README.md

---

plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.form
plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.java

also error message panel is being hidden (otherwise it has visual defect)

* idea: fixed running dialog, profile check doesn't honor wildcard profiles
