MobiVM/robovm

plugins/eclipse/ui/META-INF/MANIFEST.MF
Otherwise I wasn't able to compile the eclipse plugins, see: http://stackoverflow.com/questions/21256478/what-is-an-osgi-version-qualifier
Sorry if this is the wrong way to do it, I'm not a OSGI/Maven expert - so feel free to ignore those pulls.
=> Change Bundle-Version to 2.1.0.qualifier

compiler/compiler/src/main/java/org/robovm/compiler/plugin/shadowframe/ShadowFramePlugin.java
Otherwise java.lang.System.java fails to compile for me. ShadoFramePlugins breaks empty method getSecurityManager().
=> added check if method has only a return statement for ShadowFramePlugin

README.md
This PR would slim down the README.md in the repository and move stuff to the wiki, especially the whole dev setup. 
Also added some short usage infos with the supporting links. 
@MobiDevelop it would be great if you could open the wiki in this repository so that I can create and edit pages directly there. Currently I did it in my fork, take a look at https://github.com/florianf/robovm/wiki
Take a look at it and tell me what you think. IMHO we're really missing some documentation and guides for our users, this would be a start.
=> Slim down README.md and move things to the wiki

compiler/compiler/src/main/java/org/robovm/compiler/AppCompiler.java
Add help section for "-dump-intermediates" to the robovm cli application.
The switch already exists only the help/usage section was missing.
=> Add missing switch to help section of robovm cli

compiler/cocoatouch/src/main/java/org/robovm/apple/photos/PHAssetResourceRequestOptions.java, plugins/maven/maven-resolver/src/test/java/org/robovm/maven/resolver/RoboVMResolverTest.java
Build fails when attempting to run tests for robovm-maven-resolver as the
2.2.0-SNAPSHOT cannot be found in Sonatype Nexus Snapshots. Updating to use the 2.2.1-SNAPSHOT one instead.
Also, when compiling the following error was thrown for the PHAssetResourceRequestOptions class:
```
Compiling org.robovm.apple.photos.PHAssetResourceRequestOptions (ios x86 release)
java.lang.IllegalArgumentException: No @Marshaler found for return type of @Bridge method <org.robovm.apple.photos.PHAssetResourceRequestOptions: org.robovm.objc.block.VoidBlock1 $m$progressHandler(org.robovm.apple.photos.PHAssetResourceRequestOptions,org.robovm.objc.Selector)>
```
Adding the `@Block` annotation to the two `VoidBlock1` instances appears to correct it.
=> Fixes for build and compiler errors

plugins/maven/robovm-maven-plugin/pom.xml, pom.xml
So I went to all that trouble to get the Maven plugin in shape for inclusion in the next release, and then failed to actually reference it from the top-level POM, so it didn't go out with 2.3.0.
This includes the Maven plugin in the top-level POM so that the next Maven release will include it.
I also noted that the `plugins/maven/junit` module and `plugins/maven/maven-resolve` module are not actually needed by the Maven plugin and are only for certain kinds of testing that apparently no one is using and no one is likely to need to support, so I'll file another PR getting rid of them. No point in letting that code sit around and rot.
=> Include Maven plugin so that it gets released.

plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java
I use idea for development of robovm plugin and in dev mode it is 99% of cases required to pick up jar libraries from development location. These changes add this. 
BTW. wiki doesn't state about setting up Idea to develop/debug plugin but information is available there 
https://github.com/MobiDevelop/robovm/blob/master/plugins/idea/README.md
=> IDEA plugin updated to pickup dev jar libraries in dev DEV similar how Eclipse plugin does 

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCMemberPlugin.java, compiler/objc/src/main/java/org/robovm/objc/annotation/IBOutlet.java
functionality was in original 1.14 and useful for UIKit app. Allow to attach annotation to field instead of implementing a setter. 
Actually proposed change will generate setter for fields tagged with @IBOutlet/@IBOutletCollection
=> implemented @IBOutlet/@IBOutletCollection on class fields

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
as it causes “invalid resource directory (directory or signature have been modified)” error on frameworks with resources signed
More over it is deprecated since Xcode7 and should not be used
https://developer.apple.com/library/content/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG206
=> removed resource rules 

plugins/gradle/src/main/java/org/robovm/gradle/RoboVMPluginExtension.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMBuildTask.java
Looking into an issue with our robovm build, thought the -dump-intermediates command line option would be useful in the gradle plugin configuration.
This commit adds the ability to configure that existing flag in the gradle robovm configuration like so:
```
robovm {
dumpIntermediates = true
}
```
This defaults to false like the existing default in the config builder.
=> Exposing dump-intermediates builder option to gradle plugin config

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java
`stripArchivesConfig` should not be overwritten by the default config if it is configured via robovm.xml.
=> Fixing #127 <stripArchives> config ignored

compiler/objc/src/main/java/org/robovm/objc/ObjCBlock.java, compiler/objc/src/main/java/org/robovm/objc/RunnableAsObjCBlockMarshaler.java
Hi,
This PR fixes the issue #140: Application crashes with a bad access error when runnables or void blocks (Swift closures or Obj-c function pointers) are called from a background Java thread (e.g. a libgdx OpenGL thread). This issue was first reported as #1109 in the original RoboVM project and fixed in version 1.11.
Thanks.
=> Fix issue #140

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
Should fix https://github.com/MobiDevelop/robovm/issues/143 . As noted in https://github.com/facebook/buck/issues/798 some keys of the entitlements are stripped during the build. Prevent the if the key is in the `excludedKeys`.
=> Exclude some Entitlement keys

plugins/idea/src/main/java/org/robovm/idea/builder/RoboVmModuleBuilder.java, plugins/idea/src/main/java/org/robovm/idea/components/RoboVmBuildProcessParametersProvider.java, plugins/idea/src/main/java/org/robovm/idea/components/RoboVmProjectComponent.java
Removed references to Android related classes -- this fixes failures in recent Android Studio
Also fixes issue that it was not able to create new grade project under Idea 2017
=> Android studio/Idea fixes

plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java
in case of snapshot build idea unpacks all jars every time. and they were receiving new time stamp which caused every class in project to be rebuild. 
changes done to save time stamp of file as it was in tar file.
=> IDEA -- fixed extra rebuild of all classes after idea restart

compiler/compiler/src/main/java/org/robovm/compiler/plugin/lambda/LambdaClassGenerator.java
fixed issue of method reference (an instance method of an arbitrary object of particular type) compilation when caller and particular type are same types
https://github.com/MobiVM/robovm/issues/188
=> fixes #188

plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java
This enables Kotlin classes to be picked-up correctly with Gradle 4.0+
This used to work before Kotlin 1.1.4, but with the latest version they are now also following the new output directory convention:
https://youtrack.jetbrains.com/issue/KT-18544
=> Add support for Kotlin build dirs

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
On some apps, CodeResources is no longer generated, leading into a dead
broken link.
This leads to the following stacktrace when running gradlew createIPA --stacktrace:
```java
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':code:apps:ios:appname:createIPA'.
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTa …
```
=> No longer create a symbolic link to coderesources

plugins/debugger/src/main/java/org/robovm/debugger/jdwp/handlers/referencetype/JdwpRefTypeSourceFileHandler.java
it was a bug in JDWP request handler as it has to return only file name without path as per spec. Idea was ok with it and looks like did some sanity check.
=> fixed source lookup problem for eclipse. 

plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/RuntimeClassInfoLoader.java
This happens when evaluating internal of `native` object in debugger (NSDictionary in my case) and bound Java class for internal objects (NSDictionary$EntrySet in my case) was not loaded by Runtime. E.g. class resolution is happening by Debugger itself.
=> fixed: Debugger hangs when evaluating native objects that has no corresponding Java class loaded

compiler/compiler/src/main/java/org/robovm/compiler/plugin/lambda/LambdaPlugin.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/JdwpEventCenterDelegate.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/RuntimeUtils.java
1. It was not possible to step over code if this code was generating exception (even if it was handling it)
2. Debugger was incorrectly resolving scope of local variables if their usage was starting with invoking of lambda
=> Debugger - broken step over and crashed when using labda

plugins/templates/ios-framework/src/main/resources/archetype-resources/headers/__appName__.h, plugins/templates/ios-framework/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/Api.java, plugins/templates/ios-framework/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/__mainClass__Impl.java
it is dangerous to expose method with prefix such as “alloc”, “new”, “copy”, or “mutableCopy” to native side as ARC could consider itself as owner and will not retain object. Which will cause EXC_BAD_ACCESS after GC
=> template fix, calculator-constructor method renamed to createCalculator from ARC dangerous one

plugins/debugger/src/main/java/org/robovm/debugger/DebuggerLaunchPlugin.java, plugins/maven/plugin/pom.xml, plugins/maven/plugin/src/main/resources/META-INF/services/org.robovm.compiler.plugin.LaunchPlugin, plugins/maven/pom.xml
Contribution to #254 - enabling the `-Drobovm.debug` and `-Drobovm.debugPort` options again. The debugger seems to start and listens or connects.
=> Enabling Maven debug options

plugins/idea/src/main/resources/META-INF/plugin.xml
menu was added as part of https://github.com/MobiVM/robovm/pull/253
and it location as following 
but after period of using I've found that it more preferable to have 'Window' menu at its place. 
As it is often being used to switch projects/arrange windows. 
So RoboVM menu was moved next after Tools menu and it doesn't affect things there much
=> 'RoboVM' menu position changed to one after ToolsMenu

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/DeviceType.java
Root case: simulator name was modified by `deviceName.toLowerCase().replaceAll("-", " ")` as result any simulator that contained '-' in name was not found
=> Fix 233,  Fixed simulator pickup

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SigningIdentity.java, plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunProfileState.java
there are three commits: 
1 - fixes #286 by completing #287 in sake of delivering the fix 
2- fixes #285 -- obeys not @NotNull otherwise idea halt the plugin 
3- adds logic not extracting same file on every launch and do clear cache when new files extracted just to avoid bug cases when incompatible data stays in cache, [check post by @dthommes](https://gitter.im/MobiVM/robovm?at=5ae44a7415c9b0311445a395)
=> Bugfix 286 285 and clear cache on new snapshot

plugins/gradle/build.gradle, plugins/gradle/src/main/java/org/robovm/gradle/RoboVMPlugin.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java, plugins/gradle/src/main/resources/META-INF/services/org.robovm.compiler.plugin.LaunchPlugin, plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java
this pr contains following changes: 
1. added dependency to `build` task to force java compilation for every RoboVM task. Otherwise commands like `launchIOSDevice` will fail as java classes are not generated.
2. [cosmetic] added description to tasks
```
> gradle tasks
MobiVM tasks
------------
createIPA - Creates .ipa file. This is an alias for the robovmArchive task
launchConsole - Runs a console app
launchIOSDevice - Runs your iOS app on a connected iOS device.
launchIPadSimulator - Runs your iOS app in the iPad simulator
launchIPhoneSimulator - Runs your iOS app in the iPhone simulator
robovmArchive - Compiles a binary, archives it in a format suitable for distribution and saves it to build/robovm/
robovmInstall - Compiles a binary and installs it to build/robovm/
```  
3. added logic …
=> Gradle maintenance

compiler/compiler/src/main/java/org/robovm/compiler/config/AppExtension.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/ProvisioningProfile.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SigningIdentity.java, compiler/compiler/src/test/java/org/robovm/compiler/target/ios/ProvisioningProfileTest.java
this PR contains two related to each-other parts: 
1. it fixes auto signature/provisioning profile pickup as it was broken when was trying to pickup signature -- it resulted in random first one that matches `iPhone Developer|iOS Development` and often it doesn't match profile
2. fix for code-sign of app-extension: it is required to embed own extension provisioning profile and entitlements
3. provisioning profile is auto picked up but config was extended to allow custom profile to be specified for extension:
```xml
<appExtensions>
<extension profile="3AED05A9-5F1F-4120-9276-11980B9C88EE">OneSignalNotificationServiceExtension</extension>
</appExtensions>
```
=> fixed: app-extension code sign and auto signature/provisioning profile pickup

compiler/compiler/src/main/java/org/robovm/compiler/plugin/debug/DebugInformationPlugin.java, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/ClassInfoImpl.java
if there is no debug information -- dont try to fill in variable debug structures as they will receive wrong line numbers(Integer.MAX_VALUE) that will cause compiler to crash
=> * fixed #295. compiler crashes on kotlin data classes when compiling for debug + debugger crash

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SDK.java
Root case is SDK field is not being set in LC_VERSION_MIN_IPHONEOS MACHO command. 
Commit fixes following:
* adds `sdk_version VERSION` linker command to explicitly specify version. this is only required fix
* also changes soring logic when compares iPhone.sdk with latest iPhone11.4.sdk (symb link to iPhone.sdk) to give iPhone.sdk one lower priority. So it will not go as sysroot.
=> * fix for "WARNING ITMS-90725: "SDK Version Issue"

compiler/rt/libcore/luni/src/main/java/java/text/DecimalFormatSymbols.java
=> fixed crash due NPE in case Locale's country has "no currency" 

build.sh, plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompileTask.java
Replicates behaviour of Robovm gradle plugin. Without this patch, Kotlin classes either do not compile during build (e.g. for application class) or are not found at run time.
=> Add class paths for JVM languages other than Java.

plugins/ibxcode/src/main/java/org/robovm/ibxcode/export/IBActionExportMemberItem.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/parser/IBClassHierarchyData.java
this fixes an issue described by [Alex @avazquezdev](
https://gitter.im/MobiVM/robovm?at=5b90d82660f9ee7aa4e5c1eb)
In general it adds type specifier for IBActions in generated Xcode project. It has no affect on generated robovm code itself. 
generated Xcode header, before:
```
-(IBAction) unwindToNameList:(id) sender;
```
now:
```
-(IBAction) unwindToNameList:(UIStoryboardSegue*) sender;
```
=> * Xcode project generator: adding argument type to IBAction 

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/test/java/org/robovm/compiler/DependencyGraphTest.java
Fix compile error (List<? extends Object> cannot be converted to List<ForceLinkMethodsConfig>)
=> Missing generic for ForceLinkMethodsConfig

compiler/cocoatouch/src/main/bro-gen/intents.yaml, compiler/cocoatouch/src/main/java/org/robovm/apple/intents/CLPlacemarkExtensions.java, compiler/cocoatouch/src/main/java/org/robovm/apple/intents/NSUserActivityExtensions.java
this PR added bindings for NSUserActivity and CLPlacemark categories which were skipped. 
it was required by used as [in this post](
https://gitter.im/MobiVM/robovm?at=5c34b94d1d1c2c3f9cdf749a)
=> Intents fix: binding for NSUserActivity and CLPlacemark categories

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java, plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompileTask.java
Update: works for me, works for topic starter (Eric Nondahl).  
This shell fix `Invalid Swift Support` issue when uploading to AppleStore.
root case assumed: during #340 there was introduced defect that swift libs copy in 'SwiftSupport' also get stripped of ARM64E arch as result copy of these files were modified. As part of fix this commit does:
* fixed issue with modifying of swift libs in 'SwiftSupport'
* ~now all dynamic frameworks/libs/appext are being stripped to keep only archs same as in app (similar fix done in [rules_apple] (https://github.com/bazelbuild/rules_apple/commit/b238ee53afd6c70eed5a9346dbd834f09f96b89f)). This also reduce final IPA size~ UPDATE: reverted to strip only ARM64E
* ~as all extra arches are being stripped introduced in #340 `stripArchs` option is not …
=> Fix for `Invalid Swift Support` issue

compiler/rt/robovm/src/main/java/org/robovm/rt/Signals.java, compiler/vm/core/include/robovm/signal.h, compiler/vm/core/src/signal.c, compiler/vm/rt/robovm/org_robovm_rt_Signals.c
this PR adds preservePorts option to Sygnals.installSignals. When set to true it will save mach exception handlers before invoking callback and restore after it. It is required to pre-serve mach handlers from modification by  third party analytics such as Crashlytics.
RoboVM uses signals handlers to process null-pointer exceptions. Crash reporters often uses same signals to handle crashed and some of them terminates app. Which causes NPE even in try-catch block to crash app. More details [in old post](https://dkimitsa.github.io/2018/02/16/crash-reporters-and-java-exceptions/) 
Crashlytics additionally install task mach exception handler end intercepts javas NPE as EXC_BAD_ACCESS and reports these as crashes. 
The workaround for this is same as with signals -- restore mach port handlers to …
=> restoring mach exception handlers after initializing analytics (Crashlytics today)

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/DeviceType.java
added handling of case when `xcrun simctl list devices -j` returns simulator version in form of `com.apple.CoreSimulator.SimRuntime.iOS-12-2` instead of expected `iOS 12.2`. This happen when two xcode is installed same time. also skips not iOS targets
this hit me when I had both XCode10.1 and XCode10.2beta3 installed
=> fixed "no simulators" problem simctrl returns version as com.apple.CoreSimulator.SimRuntime.iOS-X-Y

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/ProvisioningProfile.java
This simple fix to cover case asked in [gitter](
https://gitter.im/MobiVM/robovm?at=5c9134986a3d2e230def57a4)
Root case was provisioning profile generated in Xcode as free provisioning. Due to unknown manipulations that profile had no `application-identifier` in Entitlements. This causes NPE. 
But fix in general protects against all possible broken files in `Provisioning Profiles` folder
=> fix: exception when ~/Library/MobileDevice/Provisioning Profiles/ contains corrupted file

compiler/vm/core/src/signal.c
block_thread_signal was no stored in save cycle and was reset to null in restore.
=> * fixed #364.

compiler/compiler/src/main/java/org/robovm/compiler/config/OS.java
adding PR as @Tom-Ski  forgot this minor change during 2.3.6 release. 
7.0 is almost no in field. And increasing version solves IB issue https://github.com/MobiVM/robovm/issues/354
=> min version set to 8.0, this fixes localization issues with IB

plugins/gradle/src/main/java/org/robovm/gradle/tasks/IOSDeviceTask.java
thumbv7 was default, but this not an options for ios11+ and makes not sense now. to use  thumbv7 it has to specified as parameter `-Probovm.arch=thumbv7`
=> makes arm64 default target for launchIOSDevice

compiler/cocoatouch/src/main/bro-gen/coremidi.yaml, compiler/cocoatouch/src/main/java/org/robovm/apple/coremidi/MIDINotificationMessageID.java, compiler/cocoatouch/src/main/java/org/robovm/apple/coremidi/MIDIObjectType.java, compiler/cocoatouch/src/main/java/org/robovm/apple/coremidi/MIDITransformControlType.java, compiler/cocoatouch/src/main/java/org/robovm/apple/coremidi/MIDITransformType.java
issue happened as enum value was assigned wrong marshalers for sint32 types. `ValuedEnum.AsMachineSizedSIntMarshaler` corresponds to NSInteger data type which is 32bit wide on 32 bit system, but 64 on 64 bit one. 
But  sint32 is defined as:
```
#if __LP64__
typedef signed int                      SInt32;
#else
typedef signed long                     SInt32;
#endif
```
And it is typedef to int (32 bit wide) on `LP64`( 64 bit macos/ios), and long (32 bit wide) on `ILP32`(32 bit iOS) . here [are details]
Proper marshaller is `AsSignedIntMarshaler` in this case.
=> fixed #373: wrong marshaller

plugins/eclipse/pom.xml, plugins/eclipse/ui/pom.xml
The reference to 2.3.6-SNAPSHOT in one of the Eclipse pom.xml stored in a variable has been replaced by `project.version` to avoid missing it again in the future.
=> Fixes to eclipse plugin pom.xml

compiler/vm/core/src/hooks.c
it was crashing due following set of events:
- app get stopped at breakpoint  -- this means all threads received SUSPENDED command and has to stop on next instrumented hook;
- thread with native frames exited and VM reported it as detached to JDWP server, where it gets removed; 
- vm continue cleaning up java part and calls ThreadGroup.removeThread where instrumented hooks are injected as well, where it hit check against SUSPENDED state, and thread suspended event is reported to JDWP 
-JDWP not able to find out internal representation for this thread (as it was reported as detached) and crashes. 
Fix: suppress any further reports of any kind of events for thread once it marked as detached.
=> * fixed #383

compiler/cocoatouch/src/main/bro-gen/coregraphics.yaml, compiler/cocoatouch/src/main/java/org/robovm/apple/coregraphics/CGBitmapContext.java
-  removed memory corruption bug caused by wrong usage *Ptr objects; 
- added api to accept Int/Short arrays as well;
- added logic to keep data buffer reference otherwise it might be GCed while CGBitmapContext is in use
=> * fixed #387

compiler/cocoatouch/src/main/bro-gen/avfoundation.yaml, compiler/cocoatouch/src/main/java/org/robovm/apple/avfoundation/AVCapturePhotoOutput.java, compiler/cocoatouch/src/main/java/org/robovm/apple/avfoundation/AVCapturePhotoSettings.java, compiler/cocoatouch/src/main/java/org/robovm/apple/avfoundation/AVCaptureVideoDataOutput.java, compiler/cocoatouch/src/main/java/org/robovm/apple/avfoundation/AVVideoCodecType.java, compiler/cocoatouch/src/main/java/org/robovm/apple/avfoundation/AVVideoSettings.java, compiler/cocoatouch/src/main/java/org/robovm/apple/coremedia/CMVideoCodecType.java
added AVVideoCodecType as it declared in apple source.
asFourCharCode fixed -- as it was returning 8 char string (with four zero chars)
=> * fixed #381: AVVideoSettings.setCodec not using the correct mapping

plugins/idea/src/main/java/org/robovm/idea/builder/RoboVmModuleBuilder.java, plugins/idea/src/main/java/org/robovm/idea/builder/RoboVmNewModuleEditor.form, plugins/idea/src/main/resources/template_pom.xml, plugins/maven/plugin/src/main/java/org/robovm/maven/plugin/AbstractRoboVMMojo.java, plugins/maven/plugin/src/main/java/org/robovm/maven/plugin/IOSDeviceMojo.java, plugins/templates/console/src/main/resources/archetype-resources/pom.xml, plugins/templates/ios-framework/src/main/resources/archetype-resources/pom.xml, plugins/templates/ios-single-view-no-ib/src/main/resources/archetype-resources/pom.xml
- `ios-device` mojo now uses `arm64` as default architecture (similar to gradle plugin) to minimize amount of error happened to new users when running on arm64 only devices
- all pojos now explicitly calls `compile` goal (similar to gradle plugin). just to eliminate `Failed to launch IOS Simulator: Main class xxx.Main not found` error for new users
- idea: mvn template fixed to use proper MobiVm dependencies (as it was still using org.robovm as result it was failing to sync)
- idea: mvn template updated to use 1.8 java, otherwise it was failing to compile 'ios app without storyboard' as it uses lambdas
- idea: default app name renamed from `My App` -> `MyApp` as space was breaking maven build (space is not allowed in artifactId).
- cosmetic: fixed pom.xml in templates to use java 1.8 and …
=> maven maintenance

compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java
with xcode11 location of swift libraries was changed and robovm compiler is crashing as not able to process swift lib dependencies. 
this is this moment workaround and it just adds 'swift-5.0' as one of the directories to look for swift libs. it hardcodes very specific version and to be replaced with proper solution once it is known.
=> xcode11: workaround for swift libs location

compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/AppLauncher.java, compiler/libimobiledevice/src/test/java/org/robovm/libimobiledevice/util/AppLauncherTest.java
fixed regexes and covered with tests
=> fixed crash when starting on ios13 devices while having xcode10

compiler/rt/robovm/src/main/java/org/robovm/rt/bro/ValuedEnum.java
by adding missing @MarshalsValue to toNative methods. Otherwise compiler was not able to resolve to native marshaller for enum and went to parent class where it picked up default marshaller from ValuedEnum. This results in type difference in case type of enum data is not int and caused following exception:
> java.lang.IllegalArgumentException: Duplicate @StructMember(1) in @Packed structs (union in packed structs is not supported
=> * fixed #408 

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCBlockPlugin.java, compiler/compiler/src/test/java/org/robovm/compiler/plugin/objc/ObjCBlockPluginTest.java
Compiler fails when compiling `NSOrderedCollectionDifference` with exception:  
> org.robovm.compiler.CompilerException: Unresolved type variable T in parameter 1 of @Block method
This PR fixes block method parameter resolution by resolving arguments to Java classes level eliminating TypeVariable ones from it.
=> ios13_postfix#1: compiler, fixed resolving of block argument in generic type

compiler/compiler/src/main/java/org/robovm/compiler/BridgeMethodCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/BroMethodCompiler.java
non-static @Bridge methods happen for functions binding which first argument corresponds with receiver (e.g. class name it is being put). This works for Struct and NativeObject classes but doesn't for TypedEnum and failed with exception:
> Receiver of non static @Bridge method must either be a Struct or a NativeObject.
This PR adds support for TypedEnum as receiver to allow following method to be compiled: `UIImageSymbolWeight.toFontWeight`
=> ios13_postfix#2: compiler, support for non-static @Bridge methods in ValuedEnums

compiler/compiler/src/main/java/org/robovm/compiler/ClassCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCBlockPlugin.java, compiler/compiler/src/test/java/org/robovm/compiler/StructMemberMethodCompilerTest.java
adds support for blocks in structures. this fixes following exception when compiling CMBufferHandlers:
>java.lang.IllegalArgumentException: No @Marshaler found for return type of @StructMember method <org.robovm.apple.coremedia.CMBufferHandlers: org.robovm.objc.block.Block1 getGetDecodeTimeStamp()>
> at org.robovm.compiler.MarshalerLookup.findMarshalerMethod(MarshalerLookup.java:169)
In details there are several moments and fixes:   
- Marshallers for `@Block` affected methods are generated by `ObjCBlockPlugin` in `ObjCBlockPlugin.Before` class run. The problem here is that `ClassCompiler` invokes it after `StructMemberMethodCompiler.reset` where this marshaller is required (and where exception is happening). The fix is to move reset section of method compilers below  invocation of …
=> ios13_postfix#3: compiler, adding support for @Block struct member types

compiler/compiler/src/main/java/org/robovm/compiler/ClassCompiler.java
this PR adds logic to skip bridged synthetic JVM methods added by compiler to handle overridden covariant return type methods. This fixes compiler exception while compiling `NWTxtRecord` class:
```
java.lang.IllegalArgumentException: @Bridge annotated method <org.robovm.apple.network.NWTxtRecord: org.robovm.apple.foundation.NSObject copy()> must be native
at org.robovm.compiler.BridgeMethodCompiler.validateBridgeMethod(BridgeMethodCompiler.java:87)
at org.robovm.compiler.BridgeMethodCompiler.doCompile(BridgeMethodCompiler.java:233)
```
=> ios13_postfix#3: compiler, fix for exception on JVM bridged methods with @Bridge annotation

compiler/compiler/src/main/java/org/robovm/compiler/AppCompiler.java, dist/package/pom.xml, plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java, plugins/idea/src/main/java/org/robovm/idea/builder/RoboVmModuleBuilder.java, plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompileTask.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmBeforeRunTaskProvider.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunConfiguration.java, plugins/idea/src/main/java/org/robovm/idea/sdk/RoboVmSdkType.java, plugins/idea/src/main/resources/META-INF/plugin.xml, plugins/idea/src/main/resources/template_build.gradle, pom.xml
This PR has is based on #400 so it has to be merged after it. 
- It workarounds #242 by adding task before run (and compilation happens there) 
- fixes build cancelation (build was canceled but linker was invoked)
- leaves only Gradle as build system for new projects/modules under AndroidStudio
- removes Gradle import dialog and configure gradle directly (for new projects/modules) 
Its subject for testing. 
@Tom-Ski lets merge #400 into stand alone branch and then I will update target base(now its master)
Pre-build idea plugin for testing(link updated):
https://drive.google.com/open?id=1AzGxqqF1ExoRLGqg-seLUOfXnu695b-2
=> Idea/AndroidStudio Plugin: fixed NPE  (#242) and maintenance

plugins/eclipse/pom.xml, plugins/eclipse/ui/pom.xml, plugins/idea/build.gradle, plugins/idea/pom.xml, release.sh
this PR fixes release.sh script in JDK12 branch. it was broken by new maven project tree. 
- eclipse and idea maven scripts are stand-alone now (have no parent, as it was before updates). this is required as maven version update plugins are not able to update version in PARENT section when calling not from project root;
- eclipse tycho plugin updated to stable version
=> release script: fixed bugs

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/DeviceType.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SDK.java, compiler/compiler/src/test/java/org/robovm/compiler/target/ios/SDKTest.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunProfileState.java
Simulator device type doesn't depend now on SDK available with Xcode.
Missing of iOS 13.3 SDK caused robovm to skip simulators.
=> fixed: missing iOS 13.3 simulators

compiler/vm/bc/src/CMakeLists.txt, compiler/vm/build.sh, compiler/vm/core/src/CMakeLists.txt, compiler/vm/debug/src/CMakeLists.txt, compiler/vm/frameworksupport/src/CMakeLists.txt, compiler/vm/rt/CMakeLists.txt, compiler/vm/rt/robovm/CMakeLists.txt
parallel build was broken as most of modules hadn't no dependency set to extgc as result these failed in parallel mode. 
with these dependencies android RT(has no dependency to extgc) starts building first while libatomic/bdwgc is being downloaded. once dbwgc is ready all other modules being build in parallel.
=> fix: enabling parallel build of VM native code

compiler/pom.xml, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java, plugins/resolver/pom.xml
Http is no longer supported by the repo1 maven repo and the robovm-maven-resolver test is failing due to the 501 error related to that.
https://support.sonatype.com/hc/en-us/articles/360041287334
This tweaks a few places we use http to be https and updates the shrinkwrap maven resolver to also pull in a change related to https.
=> Switch use of maven http to https since http is no longer supported.

compiler/compiler/src/main/java/org/robovm/compiler/target/framework/FrameworkTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
Fixes a bug that caused the min OS SDK check never to fail (allowing building apps with minimum version under the minimum supported one).
Also makes usage of minimum version consistent across the board and removes hardcoded values.
=> Fixes min OS version checks and removes hardcoded values

compiler/vm/core/src/call0-darwin-thumbv7.s
recent changes in [LLVM](https://reviews.llvm.org/rG6af366be8ad3199f715c54e84c779e02bb8c18b8) doesn't allow sub/add operations when Rd is SP and Rs is not (as instructions were deprecated by ARM). So code was rewritten as bellow:
from
```
sub sp, r7, #4.  ; sp = r7 - 4
```
to
```
sub r7, r7, #4. ; r7 = r7 - 4
mov sp, r7      ; sp = r7
```
Sadly have no 32 bit enabled device at hand to validate (will check once pick one)
=> * Xcode11.4: fix for `source register must be sp if destination is sp`

compiler/compiler/src/main/java/org/robovm/compiler/plugin/debug/DebugInformationPlugin.java, compiler/vm/core/src/hooks.c, plugins/debugger/src/main/java/org/robovm/debugger/delegates/InstanceUtils.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/JdwpEventCenterDelegate.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/RuntimeUtils.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/ThreadDelegate.java, plugins/debugger/src/main/java/org/robovm/debugger/jdwp/handlers/eventrequest/events/JdwpEventRequest.java, plugins/debugger/src/main/java/org/robovm/debugger/jdwp/handlers/method/JdwpMethodLineTableHandler.java, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/ClassInfoImpl.java, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/MethodInfo.java, plugins/debugger/src/main/java/org/robovm/debugger/state/instances/VmThread.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/ByteBufferReader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/MachOLoader.java, plugins/idea/src/main/java/org/robovm/idea/components/RoboVmApplicationComponent.java
* fixed: debugger crash resolving Thread objects that wasn't started
* improvement: debugger reports now only line number where breakpoint can be hit
* improvement: Idea settings: debugger/stepping filter -- extended with  `dalvik.*`, `libcore.*`
* improvement: removed synthetic bro-bridges/bro-callbacks from back-stack entries
* fixed: not working step-out (if stepping out into ignored class)
=> debugger maintaince (2020)

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
fixed runtime issue "This copy of libswiftCore.dylib requires an OS version prior to 12.2.0." by adding runtime path to /usr/lib/swift before @executable_path/Frameworks so this allows bundled iOS Swift 5 framework to be picked instead of embedded
=> fix for "libswiftCore.dylib requires an OS version prior to 12.2.0."

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCMemberPlugin.java, compiler/objc/src/main/java/org/robovm/objc/ObjCClass.java, compiler/objc/src/main/java/org/robovm/objc/ObjCObject.java
fixed crash (Failed to find a custom class to native super class mapping) when custom object is initiated from native side by its name. For example when inflating NIB.
Root case: changes to support native objective-c classes (#457) for framework. We have two copies of objc Class and robovm should be able to find parent class by both pointers.
Fix: alias added to map
=> fixed: crash when custom object instantiated from XIB

plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/MachOLoader.java
Fixed debugger crash when breakpoint is set in method where number of line is multiple of 8. this was fixed already when bptable was going to .bss section. This fix covers case when it goes to __common section.
Method example where setting of breakpoint causes a crash (method line is first line):
```
private void demo() {
System.out.println(0);
System.out.println(1);
System.out.println(2);
System.out.println(3);
System.out.println(4);
System.out.println(5);
System.out.println(6);
}
```
=> * fixed: debugger crash when setting breakpoint 

compiler/compiler/src/main/java/org/robovm/compiler/config/AbstractQualified.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/PlatformVariant.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Qualified.java
This PR makes <path> tags for extensionPaths and frameworkPaths customisable using constraints, following are:
- platform: array of supported  platform, corresponds to OS enum
- variant: array of supported platform variants (device/simulator)
- arch: array of supported platform arches  
To have one folder with only sim frameworks and another with only device use config as bellow:
```xml
<frameworkPaths>
<path variant="device">arm_libs</path>
<path variant="simulator">sim_libs</path>
</frameworkPaths>
```
=> frameworkPath/extensionPath can be qualified (temporal support for xcframeworks)

compiler/rt/libcore/crypto/src/main/java/org/conscrypt/NativeCrypto.java
native crypto updated with list of ciphers required for modern TLS1.2 servers. this fixes SSL handshake failures when using okhttp v4.x:
> javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake terminated
what were done:
- added ciphers (already available in openssl) just exposed to RT;
- JDK13 was used as reference. added only ciphers that also available in JDK13 (no need adding of deprecated)
- list of supported ciphers was re-ordered to match order of JDK13
- list of default cipher was extended with new ones and re-ordered to match order of JDK13
=> better tls1.2: few more ciphers added to runtime

plugins/debugger/src/main/java/org/robovm/debugger/delegates/InstanceUtils.java, plugins/debugger/src/main/java/org/robovm/debugger/jdwp/JdwpDebugServer.java, plugins/debugger/src/main/java/org/robovm/debugger/jdwp/handlers/vm/JdwpVmDisposeObjectsHandler.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/Converter.java
this PR deliver two fixes: 
- debugger was crashing in sequent debug session with ClassCastException (root case -- tag cache was implemented as static field and was keeping values from previous session)
- added dummy JdwpVmDisposeObjectsHandler , if returned NOT_IMPLEMENTED IntelliJ IDEA hang debug session
=> debugger: fixed crash on sequent debug sessions, fixed idea hang (rare)

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCMemberPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/target/framework/FrameworkTarget.java, compiler/vm/frameworksupport/src/frameworksupport.m
Root case of issue: JVM was started once Framework was loaded, JVM structures were not exposed, and its not possible to  initialize second JVM using JNI_CreateJavaVM.
Solution: to disable automatic VM creation `JNI_CreateJavaVM` to be exported. Its a trick instead of adding another option to robovm.xml:
```
<exportedSymbols>
<symbol>JNI_CreateJavaVM</symbol>
</exportedSymbols>
```
Also JNI based class can call back `void rvmInitializeFrameworkWithJVM(JavaVM* externalVm, JNIEnv *externalEnv);` to allow `framework support` code to pre-load objc-classes
=> * fixed: broken JNI support in case of Framework target

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java
swift libraries were picked from `swift5.0` folder.  this is ok for dynamic linkage with swift. in case of static one there are `libswiftCompatibility50.a` and `libswiftCompatibilityDynamicReplacements.a that to be looked in `swift``folder
now look up is happening in both `swift` and `swift5.0`
config was extended with `<swiftLibPaths><path>path1</path></swiftLibPaths>` configuration options to allow manually specify swift lib location
libswiftCompatibility50 references dependencies that are not picked automatically and have to be specified manually, for swift 5.1 following to be added to robovm.xml `<lib>swiftCompatibility51</lib>`
=> * fixed: #500 Build system not linking two static swift libraries

compiler/vm/core/src/class.c, compiler/vm/core/src/method.c
this PR fixes issue reported by [Subsurfer in gitter](https://gitter.im/MobiVM/robovm?at=5f175f7b43d5173b8c0da2a3)
JNI FindClass was not successful when was called from JNI_OnLoad (as result of System.loadLibrary)
root case: top java class on stack was `java.lang.Runtime` and its classLoader was NULL (corresponds to BootClassLoader). As result user class was looked in BC list and failed.
fix: use systemClassLoader in case as top java class is BC class.
issue is similar to https://github.com/robovm/robovm/issues/352
if application uses dynamic framework or library that exposes JNI_OnLoad it being called in context of application image. This happens as dyld loads all symbols from libraries referenced by LC_LOAD_DYLIB command. as result library JNI_OnLoad got called on early state while JNI …
=> jni: fixed early JNI_OnLoad, fixed use of BootClassLoader within JNI FindClass call

compiler/compiler/src/main/java/org/robovm/compiler/target/ConsoleTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/LaunchParameters.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SimLauncherProcess.java
work flow is messy as result rvm debug parameters are being injected last after user ones.
but runtimes parses rvm at startup and stop at first non rvm. as result debugger arguments are not being parsed and target starts without waiting for debugger.
reorder arguments and place rvm parameters in place.
example of wrong order (rvm will stop at -FIRDebugEnabled):
> -rvm:log=warn -FIRDebugEnabled -FIRLoggerForceSTDERR -rvm:EnableHooks -rvm:WaitForResume -rvm:PrintDebugPort=/var/folders/6.port
reordered:
> -rvm:log=warn -rvm:EnableHooks -rvm:WaitForResume -rvm:PrintDebugPort=/var/folders/6.port -FIRDebugEnabled -FIRLoggerForceSTDERR
if user specifies `-rvm` arguments the order of user arguments will be changed
=> fix: debugger was not able to attach to target if run arguments were specified

plugins/idea/build.gradle, plugins/idea/src/main/resources/META-INF/plugin.xml
* fixed `plugin defines no module dependencies (supported only in IntelliJ IDEA)`
by adding dependency to Java module as described by link
https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html
=> suport for AS4.1 canary 

compiler/compiler/src/main/java/org/robovm/compiler/config/AppExtension.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/WatchKitApp.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/DeviceType.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSSimulatorLaunchParameters.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SimLauncherProcess.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.form, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunConfiguration.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunProfileState.java, plugins/templates/console/src/main/resources/archetype-resources/robovm.xml
This PR delivers changes to allow integrating of dependent WatchOS application (built in Xcode). 
Code was tested against simulator/device/ipa target (thx to Guillermo Rodríguez).
Complete tutorial can be found in [the post](https://dkimitsa.github.io/2020/05/20/tutorial-packing-dependent-watchos-app/)
Once `watch.app` is build it can be configured in `robovm.xml` to be included in application:
```
<watchKitApp>
<app>watch.app</app>
</watchKitApp>
<appExtensionPaths>
<path>exts-sim</path>
</appExtensionPaths>
```
This PR also extends `Idea` plugin run configuration and enables to deploy to both iOS and paired watchOS targets.
=> * watchOS dependant application support (as attachment to iOS robovm app)

compiler/libimobiledevice/patches/03-fix-ios14-pr1004-fallback-secure-services.patch, compiler/libimobiledevice/patches/04-fix-ssl_read_with_timeout.patch, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/LockdowndServiceDescriptor.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/AfcClientRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/ByteArray.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/ByteArrayOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/DebugServerClientRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/IDeviceConnectionRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/IDeviceEvent.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/IDeviceRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/InstproxyClientRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/IntOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LibIMobileDevice.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LibIMobileDeviceJNI.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LockdowndClientRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LockdowndPairRecordStruct.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LockdowndServiceDescriptorStruct.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LockdowndServiceDescriptorStructOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/LongOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/MobileImageMounterClientRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/PlistRefOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/StringArray.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/StringArrayOut.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/binding/StringOut.java, compiler/libimobiledevice/src/main/native/libimobiledevice_wrap.c, compiler/libimobiledevice/src/main/swig/include/libimobiledevice/lockdown.h
its not upstream with fixes, instead patches are used:
- patch 3: adds support for DVTSecureSocketProxy service, based on https://github.com/libimobiledevice/libimobiledevice/pull/1012 with few my fixes
- patch 4: fixes SSL read with timeout (as its broken for reads more than 1 byte in length)
Also bindings were updated for these changes
=> * this enables deployment to ios14 devices

plugins/idea/src/main/java/org/robovm/idea/actions/ASNewGroup.java, plugins/idea/src/main/resources/META-INF/plugin.xml
as in case of non-AS forks of Idea -- new project/new module menus are available.
=> show `RoboVM-New` menu only in case of Android Studio

compiler/vm/core/src/hooks.c
if class matches filter for event to be reported VM code was sending an event and suspending thread. As result method invocation was never complete and debugger terminated due operation timeout.
skip suspend for case if method invocation is active
```kotlin
object Test {
fun test() {
println("Test breakpoint at this line")
}
override fun toString(): String = onLoad::javaClass.toString()
class onLoad
}
```
=> * fixed bug: debugger hangs class loaded during method invocation

compiler/libimobiledevice/patches/03-fix-ios14-pr1004-fallback-secure-services.patch, compiler/libimobiledevice/patches/04-fix-ssl_read_with_timeout.patch
Root case: time stamp was wrongly calculated -- only usec fraction was used (without seconds) to calculate time stamp. As result at matter of chance loop was never terminated by timeout.
note: libimobiledevice has to be recompiled
=> fixed: ios14 device session hang

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/util/InfoPList.java, compiler/compiler/src/main/java/org/robovm/compiler/util/PList.java, compiler/compiler/src/main/resources/Entitlements.plist
- base Plist was extracted from InfoPlist class for generic Plist parsing and value placeholder substitution(with values from property file);
- Simulator launch will use entitlements if provided in robovm.xml
- changed way how team ID is generated for simulator launch. Instead of random string for each launch it will now: checks for `teamID` key in properties. If not -- will generate MD5 from bundle id -- to keep it same each launch.
- removed hardcoded sim entitlement `keychain-access-groups` as entitlements can now be specified by user
- for entitlements for device target properties are used as well. this will allow to use placeholders if required
- removed bundled Entitlement.plist as it useless (empty)
=> Support for entitlements for simulator run (fix #529)

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
Root case: recent changes to support entitlements on simulator caused empty entitlements in projects that doesn't use it. As result verification fails with "Application is missing the application-identifier entitlement."
=> * fixed signing issue when project doen't use entitlements

compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java
issue mentioned on [gitter](https://gitter.im/MobiVM/robovm?at=5f7d9c16460354748404b65e)
root case: xcassets have to be processed in one call. otherwise each call will produce individual Assets.car that will override previous one
=> * fixed: support for multiple xcassets

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/util/io/RamDiskTools.java, compiler/compiler/src/test/java/org/robovm/compiler/AppCompilerTest.java
`First commit` fixes issue raised in [gitter](https://gitter.im/MobiVM/robovm?at=5d026f765213b626637bc705)
Reason: while constructing TMP path only `/Volumes/RoboVM RAM Disk/tmp` was created on disk. This caused tools (such as lipo) to fails as full path didn't exists. Also RamDisk prefix is not appended anymore to path if it is there already.
`Second commit` fixes issue when cleanCache failed due broken logic and RamDisk was reject to be used
`Third commit` added logic to clean up tmp/ folder. Without it RamDisk got exhausted and stop working.
=> RamDiskTools fixes

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SimLauncherProcess.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java, plugins/idea/src/main/java/org/robovm/idea/actions/CreateFrameworkAction.java, plugins/idea/src/main/java/org/robovm/idea/actions/CreateIpaAction.java, plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompileTask.java, plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompilerThread.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmBeforeRunTaskProvider.java, plugins/idea/src/main/java/org/robovm/idea/sdk/RoboVmSdkType.java, plugins/idea/src/main/resources/META-INF/plugin.xml
This PR fixed #542 and also changes the way project compilation is triggered (for IPA/Framework creation)
`CompilerManager` is not invoking build plugins such as Dagger. As result intermediate classes are not being generated and RoboVM compilation fails.
`ProjectTaskManager.build(module)` is now used with is equal to menu `Build/build module`. Once build is success -- RoboVM compiles IPA/Framework binaries.
`RoboVmCompileTask` was removed from compilation chain. This means that it will not be triggered automatically. However IPA/Framework was reworked in this fix to call it manually. Also run configuration already has manual RoboVM compilation invocation as pre-launch task
- better cancellation processing during IPA/Framework compilation
- fixed issue during SDK files installation during …
=> * fixed #542: Dagger with Kotlin, IDE IPA Creation Problem

compiler/cocoatouch/src/main/java/org/robovm/apple/coregraphics/CGRect.java, compiler/compiler/src/main/java/org/robovm/compiler/BroMethodCompiler.java
structures are not being copied and only their pointer being marshalled (same as in case of @ByRef). This causes number of bugs:
- expected the copy but struct points to source struct/value. as result changes of "copy" causes changes in the source
- struct might be located in R/O segment and any try to modify it cause GPF [gitter](https://gitter.im/MobiVM/robovm?at=5ff3acf74eba353cdf1aabff).
make a copy of structure on heap as its required by @ByVal
The fix breaks existing code that is built around this bug. An example is `CGRect` constructor that stops working:  
```java
public CGRect(double x, double y, double width, double height) {
getOrigin().setX(x).setY(y);
getSize().setWidth(width).setHeight(height);
}
```
After the fix `getOrigin()`/`getSize()` return a copy (byValue) structures. …
=> * fixed: @ByVal is not working for GlobalValues/Struct getters

compiler/cocoatouch/src/main/bro-gen/uikit.yaml, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UIKey.java
fix for #548 is not working as expected as produce:
```
org.robovm.compiler.CompilerException: Found multiple overridable @Method or @Property methods in org.robovm.apple.uikit.UIKey with the selector 'keyCode'.
```
the fix is not to use same @Property annotation but implement getKeyCode with separate implementation that calls getKeyCodeRaw
=> * hot fix for CompilerException while compiling UIKey.keyCode

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCProtocolToObjCObjectPlugin.java
all ObjC protocol bindings are interfaces in RoboVM. As result only marshalable types can be passed to native side. Anonymous classes/lambdas passed as implementation of NSObjectProtocol will cause `ClassCastException` in `ObjCObject.Marshaller`
```java
UIToolbar toolbar = new UIToolbar();
toolbar.setDelegate(bar -> UIBarPosition.Any);
```
Idea is to force classes that implement `NSObjectProtocol` and extends from `java.lang.Object` to extend from `NSObject`.  
RoboVM compiler was extended with `ObjCProtocolToObjCObjectPlugin` that responsible for:
- changing super class to `NSObject`;
- modifying initializer (constructor) code to call `NSObject.<init>()` instead of `Object.<init>()`
=> fix for: ClassCastException - passing java Interface implementation as ObjC protocol

compiler/rt/libcore/crypto/src/main/java/org/conscrypt/NativeCrypto.java, compiler/rt/libcore/crypto/src/main/java/org/conscrypt/OpenSSLSocketImpl.java, compiler/vm/rt/android/external/openssl/ssl/t1_lib.c, compiler/vm/rt/android/libcore/crypto/src/main/native/org_conscrypt_NativeCrypto.cpp
Fixed crash due multithreading. 
* [CVE-2010-3864](https://www.openssl.org/news/secadv/20101116-2.txt)
* [89408: ALPN: change socket calls to SSL_set_alpn_protos](https://android-review.googlesource.com/c/platform/external/conscrypt/+/89408)
* [68360: Tidy up locking in OpenSSLSocketImpl](https://android-review.googlesource.com/c/platform/external/conscrypt/+/68360)
=> fix for #557. merged several CryptoLib/OpenSSL fixes

plugins/idea/README.md, plugins/idea/src/main/java/org/robovm/idea/components/setupwizard/JdkSetupDialog.java
code updated as deprecated API was removed in 2021.1 EAP, readme file updated with instructions how to setup maven-based development with 2021.1 EAP
=> Idea plugin maintenance: support for 2021.1 EAP

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/SwiftSupport.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java
- allowing static swift libs to be linked by linker (no need to specify them)
- fixed pattern to not try to copy swift libs that are part of runtime, only @rpath are being copied now;
- application binary is being scanned for swift dependencies as well now. As static linking might introduce ones
- added `<swiftSupport>` config option. Putting this to `robovm.xml` will add swift path to linker library search path
=> * reworked way swift dependencies are picked up

compiler/cocoatouch/src/main/java/org/robovm/apple/coreaudio/AudioBufferList.java, compiler/cocoatouch/src/main/java/org/robovm/apple/coremidi/MIDIEventList.java, compiler/cocoatouch/src/main/java/org/robovm/apple/coremidi/MIDIPacketList.java
Issue #561 was introduced during ios13 binding generation.
To work with Flexible Array Members (FAM) its required to get pointer to the member and then navigate by it to put/get data. 
When struct member is annotated as `@ByVal` it will return a COPY of first element of FAM instead of pointer to it. 
Updating this element as array will not affect original struct (the issue itself) and is dangerous as will produce memory corruption if items changed at index 1+
=> fixed #561: reverted binding of structs with flexible array members

plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java
This is a tiny change that fixes a build error that occurs when the RoboVM Gradle plugin is run with Gradle 7.
A sample error:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':ios:createIPA' (type 'ArchiveTask').
- Type 'org.robovm.gradle.tasks.ArchiveTask' property 'roboVMLogger' is missing an input or output annotation.
Reason: A property without annotation isn't considered during up-to-date checking.
Possible solutions:
1. Add an input or output annotation.
2. Mark it as @Internal.
Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
```
As the logger is neither an input nor an output, I chose the second solution.
=> Fix Gradle plugin not working on Gradle 7

pom.xml
When building MobiVM `cmake` caches data in files called `CMakeCache.txt`. These should be removed when doing `mvn clean` otherwise the build may break if the build environment has changed since the data was cached.
This patch configures the top-level pom.xml clean task to remove any such cache files.
=> Maven clean removes CMakeCache.txt files 

compiler/compiler/src/main/java/org/robovm/compiler/plugin/desugar/StringConcatRewriter.java
Issue was reported in [gitter](https://gitter.im/MobiVM/robovm?at=61815b2bfb8ca0572bfb503d) and introduced by #558 
This happens in StringConcat desugarer in case StringBuilder class was not processed yet. And getting reference will not provide any class information. The fix is to resolve this class to make all its information available.
=> * fixed: java.lang.RuntimeException: No method void <init>() in class java.lang.StringBuilder

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/test/java/org/robovm/compiler/config/ConfigTest.java
This PR adds qualification options to libraries similar as it was done for Framework path (e.g. XCFramework support workaround). This was requested in discussion https://github.com/MobiVM/robovm/discussions/610
Second commit fixed a bug/todo related to Arm64 library/framework qualification for arm64 on simulator (corresponding UT added)
Also some amount of white space cleanup was applied by Idea.
=> Config: <lib> parameter is qualified similar to Framework path, bug fix for m1 simulator lib qualification

compiler/compiler/src/main/java/org/robovm/compiler/VTable.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/Plugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/debug/DebuggerLaunchPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/desugar/ByteBufferJava9ApiPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/desugar/StringConcatRewriterPlugin.java
Java9 adds overridden methods with covariant return types in ByteBuffer:
- flip
- clear
- mark
- reset
- rewind
- position
- limit
It becomes problem when using external dependency that was compiled as `-release 9` and caused exceptions:
> java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer
The only options is to re-compile the dependency. But it is not always possible.
This might be achieved by just adapting runtime classes but having it as Plugin allows to enable or disable the behaviour.
Desugar plugins were extended with option to disable using plugin arguments:
```
<pluginArguments>
    <argument>desugar:enableJdk9ByteBufferApi=false</argument>
    <argument>desugar:enableJava9StringConcat=false</argument>
</pluginArguments>
```
=> * desugar: added compiler plugin that extends ByteBuffer with Java9 API

compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UIApplication.java
Root case: SKStoreReviewPresentationWindow was kept in KEY_WINDOW. As result, it's dealloc wasn't called and sadly iOS15 has logic to triger code to pick another key window in SKStoreReviewPresentationWindow.dealloc.
This change might break some project that doesn't strong keep windows somewhere in AppDelegate
=> * fixed #621: iOS touch inputs not working after calling SKStoreReviewController.requestReview();

compiler/compiler/src/main/java/org/robovm/compiler/target/framework/FrameworkTarget.java, plugins/templates/ios-framework/src/main/resources/archetype-resources/headers/__appName__.h
Sadly, previous changes were not tested completely as result several use cases were not working -- like XCFramework creation when only one framework is specified (buildFat wasn't called in this case and framework wasn't picked).
Also second commit fixes Framework template for few projects by specifying NSObject superclass. Without it [ClassName alloc] is not available at native side.
Testing is ongoing but seems to be working
=> hot fix for recent Framework target changes

compiler/compiler/src/main/java/org/robovm/compiler/TrampolineCompiler.java
Reverted #589 as it wasn't fixing the root case but only symptoms. And was introducing another problem reported on [gitter](https://gitter.im/MobiVM/robovm?at=620934c66e4c1e1c8461d1cf)
Root case was exported symbol masks `*GAD*` and `*DFP*` in alt-pod configuration for Google Mobile Ads that were keeping trampolins funciton from being eliminated by `dead_strip`
Alt-pods were [fixed](https://github.com/dkimitsa/robovm-robopods/commit/b220a4f85b93b703b6ed8964ea13ca3b4257ab47) and re-deployed as well
=> * revert of #589 to fix 'duplicate symbol xxx.spfpoffset'

compiler/cocoatouch/src/main/java/org/robovm/apple/contacts/CNContact.java, compiler/cocoatouch/src/main/java/org/robovm/apple/contacts/CNContactFormatter.java, compiler/cocoatouch/src/main/java/org/robovm/apple/contacts/CNContactVCardSerialization.java, compiler/cocoatouch/src/main/java/org/robovm/apple/contacts/CNMutableContact.java, compiler/cocoatouch/src/main/java/org/robovm/apple/contactsui/CNContactViewController.java, compiler/cocoatouch/src/main/java/org/robovm/apple/cryptotokenkit/TKTokenDriverConfiguration.java, compiler/cocoatouch/src/main/java/org/robovm/apple/foundation/NSNotificationCenter.java, compiler/cocoatouch/src/main/java/org/robovm/apple/foundation/NSProcessInfo.java, compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKDecisionNode.java, compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKDecisionTree.java, compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKNSPredicateRule.java, compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKRule.java, compiler/cocoatouch/src/main/java/org/robovm/apple/gameplaykit/GKRuleSystem.java, compiler/cocoatouch/src/main/java/org/robovm/apple/scenekit/SCNTechnique.java, compiler/cocoatouch/src/main/java/org/robovm/apple/soundanalysis/SNClassificationResult.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UIAccessibilityCustomRotorItemResult.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UICollisionBehavior.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UICollisionBehaviorDelegate.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UICollisionBehaviorDelegateAdapter.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UIContextMenuConfiguration.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/UIPointerRegion.java, compiler/cocoatouch/src/main/java/org/robovm/apple/vision/VNClassifyImageRequest.java, compiler/cocoatouch/src/main/java/org/robovm/apple/vision/VNRecognizedObjectObservation.java
fix for https://github.com/MobiVM/robovm/issues/629
Root case(s):
1. some apis return id<nsobject> and accept back id.
In case of RoboVM 2.3.16 bind these types as following:
* id<nsobject> -> NSObjectProtocol
* id -> NSObject
2. there is significant moment: CocoaTouch defines all NSObject apis in NSObject protocol and keeps NSObject class empty. While RoboVM has opposite implementation: NSObjectProtocol is empty
3. RoboVM handle retain/release for NSObject subclasses and there is might be issues with NSObjectProtocol
=> * CocoaTouch: NSObjectProtocol reverted in sake of NSObject

plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java, plugins/idea/src/main/java/org/robovm/idea/components/RoboVmSdkUpdateComponent.java
This is a workaround for issues:
#630 IDEA Plugin: Reopening Project give IDE Error
major fix for it was done in #604, but seems like projects with huge amount of modules might cause delayed execution at moment where project is disposed.
Its pure workaround as corresponding code has to be refactored as uses deprecated APIS
#631 IDEA Plugin: UI Freezes
Same conditions here: project with 100+ modules. Removing `recursive()` for dependencies evaluation. This should speed-up huge projects. But will affect modules where RoboVM dependencies are obtained transitively. Anyway we have to refactor this logic to use Facet to identify module as RoboVM one
=> * idea fixes #631, #630

plugins/idea/build.gradle
- intellij dev plugin updated to 1.5.2 as there are incompatible things happened behind curtains (JBR and Idea runtime)
- fixed version specifier and updated to 2021.1 as 2020.1 failed to load from CDN
=> * idea plugin version updated to fix broken compilation

compiler/vm/core/include/robovm/hooks.h, compiler/vm/core/include/robovm/method.h, compiler/vm/core/include/robovm/types.h, compiler/vm/core/src/hooks.c, compiler/vm/core/src/init.c, compiler/vm/core/src/method.c, compiler/vm/core/src/signal.c, plugins/debugger/src/main/java/org/robovm/debugger/delegates/InstanceUtils.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/JdwpEventCenterDelegate.java, plugins/debugger/src/main/java/org/robovm/debugger/delegates/ThreadDelegate.java, plugins/debugger/src/main/java/org/robovm/debugger/hooks/HookConsts.java, plugins/debugger/src/main/java/org/robovm/debugger/hooks/HooksChannel.java, plugins/debugger/src/main/java/org/robovm/debugger/hooks/IHooksApi.java, plugins/debugger/src/main/java/org/robovm/debugger/hooks/payloads/HooksSuspendThreadPayload.java, plugins/debugger/src/main/java/org/robovm/debugger/hooks/payloads/HooksThreadStoppedEventPayload.java, plugins/debugger/src/main/java/org/robovm/debugger/jdwp/JdwpConsts.java, plugins/debugger/src/main/java/org/robovm/debugger/jdwp/handlers/thread/JdwpThreadStatusHandler.java, plugins/debugger/src/main/java/org/robovm/debugger/state/instances/VmThread.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/Converter.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/StackTraceConverter.java
debugger was able to suspend thread only when code was reaching software breakpoint -- hook callback. so hitting "pause" in debugger in general wasn't doing anything if there was no hook instrumented java code running (e.g. threads are waiting on lock/sleep or running native message loop).
Also debugger wasn't picking JDWP thread statuses like sleeping/monitor etc.
thread status was not propagated from VM (hooks) to JDWP and was solved by extending the protocol.
interrupt any random thread is possible by sending a signal to it. There is already two signals dedicated to RoboVM and introducing another one would be wastefully.
Lucky for us one signal was used to capture thread stack trace. Last ones also good to have when you suspend the thread. So it was extended to provide a callback to …
=> * debugger - enhancement: proper thread status and suspend any thread

compiler/compiler/src/main/java/org/robovm/compiler/AppCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/Version.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/SwiftSupport.java, compiler/compiler/src/main/java/org/robovm/compiler/llvm/debug/dwarf/DICompileUnit.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/test/java/org/robovm/compiler/VersionTest.java, plugins/eclipse/ui/src/org/robovm/eclipse/RoboVMPlugin.java, plugins/gradle/src/main/java/org/robovm/gradle/RoboVMPlugin.java, plugins/idea/src/main/java/org/robovm/idea/RoboVmPlugin.java, plugins/idea/src/main/java/org/robovm/idea/builder/RoboVmModuleBuilder.java, plugins/idea/src/main/java/org/robovm/idea/sdk/RoboVmSdkType.java, plugins/junit/client/src/test/java/org/robovm/junit/client/TestClientTest.java, plugins/maven/plugin/src/main/java/org/robovm/maven/plugin/AbstractRoboVMMojo.java, plugins/maven/surefire/src/main/java/org/robovm/maven/surefire/RoboVMSurefireProvider.java
Swift library lookup was hardcoded to look for libs only in `swift-5.0` folder which is not completely valid today and causes failure to link with swift-based dependencies. 
- fixed: manual provided path in swift support were extended with $platform suffix as result it was not possible to use SDK lib location (/usr/lib/swift) as it was extended with platform;
- updated swift library order lookup. there was TODO and only 5.0 folder was added now order of swift libraries is built as bellow:
* `/usr/lib/swift`
* version less `swift`
* all versioned location like `swift-5.0` in reverse order (higher first)
- `swiftSupport` extended with `<copySwiftLibs>fals</copySwiftLibs>` option that controlls if swift runtime libraries are going to be copied or not.
- `swiftSupport` now must be added to …
=> changes in swiftSupport logic

compiler/compiler/src/main/java/org/robovm/compiler/plugin/lambda/LambdaClassGenerator.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/lambda/LambdaPlugin.java
Code to reproduce:
```
package a;
public class A {
protected foo(){};
}
package b;
import a.A;
public class B extends A{
public void test() {
Runnable r = ::foo;
r.run();
}
}
```
Root case: labda for B class is located in `package b` and can access protected members of A class from there.
Fix: for such kind of lambda a trampoline method is generated in calling class (which has all access to destination member) and instead of directly invoking method target -- this trampoline is invoked:
```
public class B extends A{
public void test() {
Runnable r = lambda(this);
r.run();
}
static private lambda$1$run(B thiz) {
thiz.foo();
}
}
public class lambda implements Runnable {
private final B thiz;
lambda(B thiz) { this.thiz = thiz; }
public void run() {
B.lambda$1$run(thiz);
}
}
```
=> * fixed: #641 java.lang.IllegalAccessError: Attempt to access protected method from Lambda

plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/ClassInfoLoader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/CompositeDataBuffer.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/CompositeDataBufferReader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/CompositeDataBufferWriter.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/DataBufferReader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/DataBufferReaderWriter.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/DataBufferWriter.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/DataByteBufferReader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/DataByteBufferWriter.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/NullDataBufferReader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/MachOConsts.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/MachOLoader.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/cmds/LinkeditDataCommand.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/cmds/SegmentCommand.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/structs/DyLdChainedFixups.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/structs/Section.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/tools/Bits64.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/tools/ChainedFixup.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/tools/ExportedSymbolsParser.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/tools/RegionSquasher.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/macho/tools/Trie.java
Starting from Xcode13 and for ios15 target Apple have changed a binary and its address references are mixed with meta data that doesn't allow debugger to parse RoboVM structures. 
This results in debugger crash on startup:
>[ERROR] Couldn't start application
>java.lang.IllegalArgumentException: there is no region for addr @10000101effaa0
>	at org.robovm.debugger.utils.bytebuffer.CompositeDataBuffer.setPosition(CompositeDataBuffer.java:37)
this PR adds support for chained fixup based on DYLD sources. It includes:
- parsed LC_DYLD_CHAINED_FIXUPS, pointer being fixed up to fixups organized in chains. Code based on [dyld](https://opensource.apple.com/tarballs/dyld/) code, mostly its a port of
`MachOLoaded::fixupAllChainedFixups` method;
- support for LC_DYLD_EXPORTS_TRIE -- another way how …
=> * Debugger: support for chained fixup 

compiler/compiler/src/main/java/org/robovm/compiler/AttributesEncoder.java, compiler/compiler/src/main/java/org/robovm/compiler/ClassCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/llvm/StructureConstant.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java, compiler/vm/bc/src/aligned.h, compiler/vm/bc/src/classinfo.c, compiler/vm/core/src/attribute.c, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/ClassInfoImpl.java, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/ClassInfoLoader.java, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/FieldInfo.java, plugins/debugger/src/main/java/org/robovm/debugger/state/classdata/MethodInfo.java, plugins/debugger/src/main/java/org/robovm/debugger/utils/bytebuffer/DataBufferReader.java
1. attribute/class info structs: these are now generated to be not packed (will consume a bit more ram)
2. VM code updated to new structure layouts
3. Debugger code updated to new structure layouts
as information structures are not packed it will increase memory requirement to keep these.
On sample project it increases size of structs from `5525197` to `6935824` bytes or by `25%`
- `-w` that was suppressing all warnings 
- `-no_pie` -- as it is not supported for arm targets (and debugger can handle it) 
- `-sdk_version` as linker picks one from `platform_version`
=> * fix for `ld: unaligned pointer(s) for architecture arm64`

plugins/idea/src/main/java/org/robovm/idea/actions/CreateFrameworkDialog.java, plugins/idea/src/main/java/org/robovm/idea/actions/CreateIpaDialog.java, plugins/idea/src/main/java/org/robovm/idea/components/setupwizard/JdkSetupDialog.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmConsoleRunConfigurationSettingsEditor.java
Root case: wrong params were used: choseFiles=true, choseDir=false
Descriptor is defined as bellow:
```
/**
* Use {@link FileChooserDescriptorFactory} for most used descriptors.
*
* @param chooseFiles       controls whether files can be chosen
* @param chooseFolders     controls whether folders can be chosen
* @param chooseJars        controls whether .jar files can be chosen
* @param chooseJarsAsFiles controls whether .jar files will be returned as files or as folders
* @param chooseJarContents controls whether .jar file contents can be chosen
* @param chooseMultiple    controls whether multiple files can be chosen
*/
public FileChooserDescriptor(boolean chooseFiles,
boolean chooseFolders,
boolean chooseJars,
boolean chooseJarsAsFiles,
boolean chooseJarContents,
boolean chooseMultiple) …
```
=> * fixed: IDEA missing OK button in directory picker

compiler/compiler/src/main/java/org/robovm/compiler/AppCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/ClassCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/Linker.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/AbstractPath.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/Clazz.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/ClazzInfo.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/Clazzes.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/MethodInfo.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/Path.java, compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/AbstractCompilerPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/BuildGarbageCollectorPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/CompilerPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/Target.java, compiler/compiler/src/test/java/org/robovm/compiler/AppCompilerTest.java
fix for #150 
- during compilation required up to 6.5Gb of heap;
- once compilation is finished and app started on simulator -- was consuming 3.4Gb of heap.
Issue discovered in Framework target: class information was required to build list of NSObject subclasses for registration but at this moment soot was disposed
Reworking into plugin fixed this issue as we follow plugin notification cycle and GC plugin is called last.
Also having it as plugin allows to disable this functionality through robovm.xml by using `buildGC:enable=false` plugin argument
- 4GB heap settings is enough to compile sample project;
- most consuming moment was about 2.7 GB after garbage collector;
- when compilation is complete and app is started memory usage is ~300MB (UI responsible, debugger happy);
- compilation …
=> * Memory usage optimization (1/2): release not required data asap

compiler/rt/robovm/src/main/java/org/robovm/rt/bro/Runtime.java
Actually -- not. If started with stderror redirection `open --stdout=0.log --stderr=1.log -W /Applications/test_app.app` following exception was observed: 
>java.lang.UnsatisfiedLinkError: Library 'UIKit' not found
at org.robovm.rt.bro.Runtime.getHandle(Runtime.java:317)
at org.robovm.rt.bro.Runtime.loadLibrary(Runtime.java:191)
at org.robovm.rt.bro.Bro.bind(Bro.java:60)
at org.robovm.objc.ObjCRuntime.bind(ObjCRuntime.java:92)
at org.robovm.apple.uikit.UIResponder.<clinit>(UIResponder.java:53)
at com.mycompany.myapp.Main.main(Main.java:89)
library search path for `iOSSupport` was missing
Manually add search path:
```
public static void main(String[] args) {
Runtime.addSearchPath("/System/iOSSupport/System/Library/Frameworks/");
```
=> * fixed: crashing sideloaded app on m1 (fix for #659)

compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java
Problem: linker error like this:
> ld: .../swift/iphoneos/libswiftCompatibilityConcurrency.a(CompatibilityConcurrency.cpp.o), building for iOS Simulator,
> but linking in object file built for iOS, for architecture arm64
Root case: old code that was targeting device if arch is `arm`. But should also check `environment` for simulator
=> * fixed: `swiftSupport` was picking iphoneos for m1 arm simulator and failed to link

compiler/vm/core/src/class.c
Crash log looks like bellow:
```
Crashed: Thread
0  libsystem_kernel.dylib         0x1d5219414 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1f2d74b50 pthread_kill + 272
2  libsystem_c.dylib              0x1b06f7b74 abort + 104
3  RoboVMMobile                   0x1060a77b0 rvmCreateVM + 4386699184
4  RoboVMMobile                   0x1060a51ec rvmInitialize + 4386689516
5  RoboVMMobile                   0x10609d9a8 _bcInitializeClass + 4386658728
```
Root case:
`rvmFindLoadedClass` was doing not synchronized access to loaded class map
=> * Fixed: `rvmCreateVM SIGABRT` during concurrent class load

compiler/cocoatouch/src/main/java/org/robovm/apple/foundation/NSNull.java
Corresponding code added manually as corresponding code is declared in QuartzCore as extension while NSNull is being parsed from Foundation.
Declared in QartzCore as bellow:
```
/** NSNull protocol conformance. **/
@interface NSNull (CAActionAdditions) <CAAction>
@end
```
=> * fixed: #665 NSNull does not implement CAAction

compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java
its a regression after M1 support: `.isArm()` doesn't mean device target anymore, to filter out simulator `environment` check to be done
currently compiler will try to copy swift dynamic libraries but these lack `arm64-simulator` slice and `arch strip` will fail that block launch on simulator. described behaviour is an another issue itself -- we should not try to copy swift dylibs in case of `arm64-simulator` but its to be provided as standalone PR
=> * fixed: in case of simulator, embedded frameworks/dylibs were stripped for not required arches

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/SwiftSupport.java, compiler/compiler/src/test/java/org/robovm/compiler/config/ConfigTest.java, compiler/compiler/src/test/resources/org/robovm/compiler/config/ConfigTest.console.xml, compiler/compiler/src/test/resources/org/robovm/compiler/config/ConfigTest.ios.xml
as mentioned in #669 its nice to have it enabled to ths compatibility with 2.3.16.
same time added option to disable `swiftSupport` block in case it causes issues, can be turned off with
`robovm.xml` entry:
```
<config>
<swiftSupport>
<enable>false</enable>
</swiftSupport>
</config>
```
=> * fixed #669: this enables swift support by default with option to disable it

compiler/compiler/src/main/java/org/robovm/compiler/ClassCompiler.java
2.3.17 release failed due this, discussion in [gitter](https://gitter.im/MobiVM/robovm?at=62c46d953bbb38488900ddee)
when Java18 used as compiler JDK-8272564 changes will be applied this will affect invocation of
java.lang.Object methods on interface receivers.
as per changes invokevirtual is replaced with invokeinterface and these methods
has to be resolved as per https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.4.3.4 item 3
in RoboVM case this means that final methods of "java.lang.Object" has to be available for lookup,
thus changes added to include [lookup] wrappers for final methods in this case
otherwise it will fail during linking with message(s):
> Undefined symbols for architecture arm64:"[j]java.lang.Object.notifyAll()V[lookup]"
=> * fix: support for classes compiled with Java18 (JDK-8272564)

compiler/compiler/src/main/java/org/robovm/compiler/target/framework/FrameworkTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java
it uses `symbols` that part of Xcode/Bin to produce symbol files from dsym same as xcode doe
=> * embedding Symbols into IPA to allow crashes from iTunes connect to be symbolicated

compiler/vm/bc/src/aligned.h, compiler/vm/core/src/attribute.c
introduced in https://github.com/MobiVM/robovm/pull/639
struct member alignment was wrongly calculated for jlong and double: was calculated as aligned by member size (8 bytes) but has to be 4 byte boundary.
```
import java.lang.annotation.*;
@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@interface SampleAnnotation {
long first();
String last();
}
public class Test {
@SampleAnnotation(first = 33, last = "last")
private String myField;
public void test() {
try {
Annotation[] anns = this.getClass().getDeclaredField("myField").getDeclaredAnnotations();
for (Annotation a : anns) {
System.out.println(((SampleAnnotation) a).first());
System.out.println(((SampleAnnotation) a).last());
}
} catch (NoSuchFieldException e) {
throw new RuntimeException(e);
}
}
}
```
use `offsetof` …
=> * fix: annotations are broken on 32 bit targets in 2.3.18

compiler/compiler/src/main/java/org/robovm/compiler/TrampolineCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/AbstractCompilerPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/CompilerPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/desugar/ByteBufferJava9ApiPlugin.java
these methods are added when ByteBuffer is compiled. At next session ByteBuffer class is considered compiled and its structure only parsed (and not desugared) as result de-sugared methods are not present in SootClass as result this produces `java.lang.NoSuchMethodError` compilation time.
trampoline compiler allows now compiler plugin to resolve missing methods. ByteBuffer de-sugaring plugin in this case returns references to target methods.
=> * fixed: de-sugared ByteBuffer (java9) calls are not visible at second compilation session

compiler/objc/src/main/java/org/robovm/objc/ObjCObject.java
when init return nil -- it calls `-release` on allocated object. but objc code was keeping old handle returned by `+alloc`. as result when Java object with this handle was disposed by GC -- it was calling `-release` on this zombie handle that caused EXC_BAD_ACCESS
=> * fixed: #684 -- crash on GC when releasing object that fails to `init`

compiler/compiler/src/main/java/org/robovm/compiler/Access.java, compiler/compiler/src/main/java/org/robovm/compiler/TrampolineCompiler.java, compiler/compiler/src/main/java/org/robovm/compiler/clazz/Clazzes.java, pom.xml
this implements nest based access control as specified in [JEP181](https://openjdk.java.net/jeps/181). This is reproducible with Java11 class files. Sample to reproduce: 
```
public class Test {
private int a;
public void foo() {
DispatchQueue.getMainQueue().async(new Runnable() {
@Override
public void run() {
System.out.println(a);
}
});
}
}
```
Gradle settings:
```
sourceCompatibility = 11
targetCompatibility = 11
```
also fixes https://github.com/MobiVM/robovm/issues/652
it covers only compilation time access control. Runtime (reflection one) is not covered.
https://github.com/MobiVM/soot/pull/3/files
=> Limited support for JEP181 Nestbased access control

compiler/compiler/src/main/java/org/robovm/compiler/AbstractMethodCompiler.java
fix for #699 
root case: introduced by removing x86 arch https://github.com/MobiVM/robovm/pull/695
error message sample:
```
duplicate symbol '_[J]sun.misc.Unsafe.putLongVolatile(Ljava/lang/Object;JJ)V' in:
[ERROR] 12:44:48.131     ~/alpods-failure-test/ios/robovm-build/tmp/iOS/ios/arm64-simulator/linker2.o
[ERROR] 12:44:48.131     ~/.robovm/cache/ios/arm64-simulator/release/Users/dkimitsa/robovm-m1/compiler/rt/target/robovm-rt-2.3.19-SNAPSHOT.jar/sun/misc/Unsafe.class.o
```
=> * fixed: (regression) functions are generated as strong and this breaks tree-shaking.

README.md, compiler/compiler/src/main/java/org/robovm/compiler/AppCompiler.java, plugins/idea/README.md
- link to http://robovm.mobidevelop.com replaced with https://mobivm.github.io #620
- mentioned recent versions of ios/xcode
- idea plugin readme updated (generic path, mentioned issue with maven project importer)
- disabled version check as endpoint doesn't seem to be working, and we should respect GDPR (e.g. ask user before using)
=> * web links updated, disabled update check

compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/AppLauncher.java
on ios13 secure service name shall be used to start debug service, before it was done in native part of ilibmobiledevice but after migrating to recent version it was lost
introduced in #696
=> * fixed: robovm failed to start application on ios13+ devices

README.md
Status of master branch matters not PRs (these can fail and there are multiple of these opened). Failing PR status should not be displayed on root README.md
=> * readme: badge changed to show status of snapshot build and not pullrequest testing

compiler/compiler/src/main/java/org/robovm/compiler/config/tools/LinkerOptions.java, compiler/compiler/src/main/java/org/robovm/compiler/target/AbstractTarget.java
this is being asked time-to-time. usually is is not required as can be covered by robovm, however it might be required for custom builds. 
to be configured using robovm.xml, sample config:
```
<config>
<tools>
<linker>
<flags>
<flag>-fembed-bitcode</flag>
<flag>--other-flag</flag>
</flags>
</linker>
</tools>
</config>
```
=> * option to customize arguments passed to linker

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, plugins/gradle/README.md, plugins/gradle/build.gradle, plugins/gradle/src/main/java/org/robovm/gradle/RoboVMGradleException.java, plugins/gradle/src/main/java/org/robovm/gradle/RoboVMPlugin.java, plugins/gradle/src/main/java/org/robovm/gradle/RoboVMPluginExtension.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMBuildTask.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractSimulatorTask.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/ConsoleTask.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/IOSDeviceTask.java
- closed #701
- removed unused license parameter
- suppressed "warning: no comment" when building gradle plugin
- updated README.md
- displaying info message "Checking for RoboVM SDK (downloading if required)..." as getting SDK files from maven could take a while first time
- introduced RoboVMGradleException that aggregates error messages from cause exceptions, allows to have more detailed output:
```
* What went wrong:
Execution failed for task ':launchIPhoneSimulator'.
> Failed to launch simulator
Failed to read project RoboVM config file in /Users/dkimitsa/IdeaProjects/empty4del2
ParseError at [row,col]:[17,7]
Message: The element type "frameworks" must be terminated by the matching end-tag "</frameworks>".
```
instead of
```
* What went wrong:
Execution failed for task …
```
=> * maintenance -- gradle

compiler/rt/libcore/libdvm/src/main/java/sun/misc/Unsafe.java, compiler/vm/rt/robovm/sun_misc_Unsafe.c
As seen in 9d99692f785588dc18c63f7cbad2ed628e97fc3d , I add a support for double too. I spot this while using Kryo library, quite popular in libGDX world (https://github.com/EsotericSoftware/kryo/blob/master/src/com/esotericsoftware/kryo/serializers/UnsafeField.java#L214).
The change should be quite harmless, but someone more expert then me should really look at it carefully. I'm just proposing a fix, maybe it's wrong, but I'd really appreciate to get this fixed in a way or another... Seems a small feature but has a huge impact in my use case.
Many thanks!
=> Add support for putDouble and getDouble from Unsafe.

compiler/vm/CMakeLists.txt, compiler/vm/rt/robovm/java_lang_System.c
was `iOS` instead of `iOS Simulator`
reported on [gitter](https://matrix.to/#/!mqUEluorTjXZPncMfe:gitter.im/$gVM8XjXRPOAvmiAb4Wpog8Rpf8p7ChGyyEtG1q51-xA?via=gitter.im&via=matrix.org)
=> * fixed: wrong `os.name` on arm64 simulator

compiler/compiler/src/main/java/org/robovm/compiler/config/tools/ActoolOptions.java, compiler/compiler/src/main/java/org/robovm/compiler/config/tools/Tools.java, compiler/compiler/src/main/java/org/robovm/compiler/util/ToolchainUtil.java
- originally was reported in #636 (support for alt icons)
- also if xcassets contain multiple icons -- random one was picked for the app
- also if xcassets contain multiple launch images -- random one was picked for the app 
`robovm.xml` was extended with `actool` options:
```
<config>
<tools>
<actool>
<appIcon>AppIcon</appIcon>
<includeAllAppIcons>true</includeAllAppIcons>
</actool>
</tools>
</config>
```
new parameters:
- `appicon` - specifies which icon to use for app (in case of multiple)
- `launchImage` -- specifies which launchImage to use (in case of multiple)
- `includeAllAppIcons` -- will add `--include-all-app-icons` command line argument to include all app icons
- `args` -- allows to add raw arguments for actool
=> * actool: support for AltIcons and other options

compiler/compiler/src/main/java/org/robovm/compiler/config/ResolvedLocations.java, compiler/compiler/src/main/java/org/robovm/compiler/plugin/debug/DebuggerLaunchPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/AppLauncherProcess.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/LockdowndClient.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/MobileImageMounterClient.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/AppLauncher.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/AppLauncherCallback.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/DeveloperImageResolver.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/Lambdas.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/Version.java, compiler/libimobiledevice/src/test/java/org/robovm/libimobiledevice/util/DeveloperImageResolverTest.java, plugins/debugger/src/main/java/org/robovm/debugger/Debugger.java, plugins/debugger/src/main/java/org/robovm/debugger/DebuggerConfig.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmRunProfileState.java, pom.xml
(also possibly fixes part of #721 issues)
libmobiledevice was failing on every situation then: device is not connected, blocked or pairing not complete. considering build process and deployment might take minutes its sad to fail just due to blocked device. changes: mitigation for these cases done by allowing 20 seconds for user to act to solve the situation:
- if no device connected -- waiting for device
- if device is locked -- waiting for unlock
- if pairing in progress -- waiting to complete
now it looks as bellow in RoboVM log window:
```
[INFO] 19:26:28.376 Build done
[INFO] 19:26:28.377 Launching executable
[INFO] 19:26:28.387 Waiting for device: No devices connected. (retry 1 of 20)...
[INFO] 19:26:29.393 Waiting for device: No devices connected. (retry 2 of 20)...
[INFO] …
```
=> * libmobiledevice maintenance: waiting for device and error handling

compiler/cocoatouch/src/main/java/org/robovm/apple/foundation/NSAttributedString.java, compiler/cocoatouch/src/main/java/org/robovm/apple/uikit/NSAttributedStringExtensions.java
this fixes #608
```
public NSAttributedString(NSURL url, NSAttributedStringDocumentAttributes options) throws NSErrorException {
super((SkipInit) null);
long h = NSObject.alloc(ObjCClass.getByType(NSAttributedString.class));
initObject(NSAttributedStringExtensions.init(ObjCObject.toObjCObject(NSAttributedString.class, h, NSObject.FLAG_NO_RETAIN), url, options, null));
}
```
it creates two java object for same handle:
- one with ObjCObject.toObjCObject.toObjCObject(ObjCObject() with option FLAG_NO_RETAIN (so it doesn't own native part)
- and second NSAttributedString itself
but both of these do release a handle on dispose() that causes the crash
no need in creating intermediate Java object, `-init` like selectors should operate on pointer level
=> * fixed: #608 NSAttributedString causes crash on next GC

compiler/compiler/src/main/java/org/robovm/compiler/ClassCompiler.java
In case of Java11 there is no accessor for private static fields are being generated and Nested classes access fields of Nested host directly. #653 added support for this but it fails for static fields as corresponding clinit wrapper wasn't generated. It cased linker failure with message:
> [ERROR] 11:52:48.616 Undefined symbols for architecture arm64:
>  [ERROR] 11:52:48.616   "_[j]org.package.ImportDialog.lastScrollY(F)[set][clinit]", referenced from:
=> * clinit accessor for private static field: to support JEP181(java11)

compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/AppLauncher.java
this happens when running app on freshly booted device. iOS 16.5 return success status even if dev image is not mounted. In this case  ImageSignature field is empty. fix: consider as not mounted if ImageSignature is not provided
=> * fixed: LOCKDOWN_E_INVALID_SERVICE when starting DebugServerService

compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/AfcClient.java
as due intercepted previous upload it might contain files that might cause different side effect. or even will block upload due AFC_E_OBJECT_EXISTS errors
=> * device deployment: clean up destination folder in staging location before uploading

compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/AfcClient.java
introduced by https://github.com/MobiVM/robovm/pull/736
```
[ERROR] 12:45:08.052 AppLauncher failed with an exception:
[ERROR] 12:45:08.052 org.robovm.libimobiledevice.LibIMobileDeviceException: AFC_E_OBJECT_NOT_FOUND
[ERROR] 12:45:08.052 	at org.robovm.libimobiledevice.AfcClient.checkResult(AfcClient.java:627)
[ERROR] 12:45:08.052 	at org.robovm.libimobiledevice.AfcClient.removePathAndContent(AfcClient.java:429)
[ERROR] 12:45:08.052 	at org.robovm.libimobiledevice.AfcClient.upload(AfcClient.java:515)
```
=> * device deployment: hotfix -- AFC_E_OBJECT_NOT_FOUND if directory doesn't exist

compiler/rt/libcore/libdvm/src/main/java/java/lang/Class.java
Add cause to exception. 
Cases where InstantiationException is created with no detail message, we don't see true error.
We also do not cause full cause in stacktrace.
Example case of NoClassDefFoundError being thrown during reflection based init of a Class, results in just a basic message of InstantiationException, not showing correct line number of issue or message of true cause.
=> Class InvocationTargetException add throwable cause

compiler/vm/core/src/memory.c
https://github.com/libgdx/libgdx/issues/7212 
GC code was setting up mark handler only for direct subclass of Struct class to mark its native structure content during GC mark phase. As result memory behind native struct area was release and available for allocations. As result this area was taken by next requested object/data. That caused crashed related to ObjC marshalling, like `objc[503]: Attempt to use unknown class 0x104094d80.` But all pointer extended intermediate classes after Struct: in this case NSErrorPtr->Ptr->Struct 
Code changed to check for subclass instead direct subclass. 
```
void test2() {
NSObjectPtr ptr = new NSObjectPtr();
NSObject o = new NSObject();
ptr.set(o);
for (int i = 0; i < 100_000_000;i++) {
new NSObject();
if (VM.getLong(ptr.getHandle()) != o.getHandle()) …
```
=> * fixed: libgdx/7212 -- crash when getting value by pointer, affected by GC

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java
otherwise existing ZIP's content is being updated as result it receives extra files (like debug symbols) that cause size increase. Also it might cause CodeSign to be invalid as it might contain not covered files
=> * fixed 744: delete existing IPA when packaging new one

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/ConfigXmlEntries.java, compiler/compiler/src/main/java/org/robovm/compiler/config/ResolvedLocations.java, compiler/compiler/src/test/java/org/robovm/compiler/config/ConfigTest.java
(also includes changes from https://github.com/MobiVM/robovm/pull/729)
SimpleXML is quite old and outdated. And it would be nice to switch to another XML bindings such as Jackson/JAXP but all of them doesn't allow xml string mutation required for property values substitutions (e.g. ` <executableName>${app.executable}</executableName>`)
SimpleXML issue: it allows unexpected tags to be present while parsing list, this caused side effect like empty text tags or null objects inserted into the list, for example
```
<frameworks>
<wrong><framework>aaaa</framework><wrong/>
</>
```
would result in (null, "aaaa") in list (beside the fact that structure is wrong)
General approach for a workaround is change List field type to custom POJO and make its serialization strict:
E.g. instead of
``` …
```
=> * fixed: strict rules for elements in lists inside robovm.xml

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCMemberPlugin.java, compiler/compiler/src/main/java/org/robovm/compiler/util/generic/SootClassUtils.java, compiler/objc/src/main/java/org/robovm/objc/ObjCClass.java
ObjCClass preloads all instances of ObjCObject to find out if these have NativeObject annotations. As result inner class might be loaded before hosting class. This makes Idea debugger not happy and it ignores CLASS_PREPARE event and doesn't apply breakpoints to it. https://youtrack.jetbrains.com/issue/IDEA-332794
Lets preload host classes before all ObjCObject classes.
NB: affects only debug builds
=> * workaround: idea debugger doesn't stop in Inner classes that extends from ObjCObject

compiler/compiler/src/main/java/org/robovm/compiler/plugin/objc/ObjCProtocolToObjCObjectPlugin.java, plugins/idea/src/main/java/org/robovm/idea/inspection/ClassWithProtocolShouldExtendNSObject.java, plugins/idea/src/main/java/org/robovm/idea/inspection/RvmCommonClassNames.java, plugins/idea/src/main/java/org/robovm/idea/inspection/RvmCommonUtils.java, plugins/idea/src/main/java/org/robovm/idea/inspection/RvmInspectionBundle.java, plugins/idea/src/main/java/org/robovm/idea/inspection/quickfix/ChangeSuperClassFix.java, plugins/idea/src/main/java/org/robovm/idea/inspection/quickfix/NavigateToClassFix.java, plugins/idea/src/main/resources/META-INF/plugin.xml, plugins/idea/src/main/resources/inspectionDescriptions/ClassWithProtocolShouldExtendNSObject.html, plugins/idea/src/main/resources/robovm/RvmInspectionBundle.properties
it fixes following case 
```java
public class Test {
public void test() {
new Delegate();
}
private static class Delegate implements NSObjectProtocol {
}
}
``` 
causes compilation warning:  
> ObjCProtocol to NSObject failed: too many public constructors
and runtime crash if this class is used as `NSObjectProtocol` with `ObjC`:
> Delegate cannot be cast to org.robovm.objc.ObjCObject at org.robovm.objc.ObjCObject$Marshaler.protocolToNative
But in case of private classes there is additional synthetic public constructor is created. Code updated to ignore synthetic constructors and allow multiple constructors to be available
Added Intellij Idea ispections to highlight following cases:
- if class implements NSObjectProtocol and extends `java.lang.Object` -- warning with quick fix to extend …
=> * fixed: ObjCProtocol to NSObject promoter in case of private classes and multiple constructors

compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/AfcClient.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/IDevice.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/InstallationProxyClient.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/MobileImageMounterClient.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/util/AppLauncher.java
- also removing duplicates if both Network and USB connection available to same device
=> * fixed: device deployment -- fails to pick exact device if multiple is connected

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/ProvisioningProfile.java, compiler/libimobiledevice/src/main/java/org/robovm/libimobiledevice/IDevice.java, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.form, plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.java
Auto detection of bundle id from module - Adds display in run config window.
Compatibility checking with signing certificate, profile, entitlements and device to help users debug before its too late (At the end of compilation)
=> Run config enhancements

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/DeviceType.java
Root cases:
- there is no more default `iPhone 8` in recent xcodes.
- have to check for prefix instead of exact match (as there is usually revision suffix)
=> * fixed: idea run configuration -- preferred simulator type was not working

plugins/gradle/build.gradle, plugins/gradle/src/main/resources/META-INF/gradle-plugins/robovm.properties
Closes #765.
https://plugins.gradle.org/docs/publish-plugin
=> Support publishing Gradle plugin marker artifact

plugins/eclipse/pom.xml
When i build `MobiVM/robovm` i get a build error with the Eclipse plugin:
```sh
$ ./build.sh
...
[INFO] RoboVM for Eclipse Core and UI ..................... FAILURE [  0.500 s]
[INFO] RoboVM for Eclipse Feature ......................... SKIPPED
[INFO] RoboVM for Eclipse Update Site ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.255 s
[INFO] Finished at: 2024-03-30T18:01:06+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.3:validate-classpath \
(default-validate-classpath) on project …
```
=> Upgrade eclipse tycho and update site

plugins/idea/src/main/java/org/robovm/idea/running/RoboVmIOSRunConfigurationSettingsEditor.java
exception:
> java.lang.NullPointerException: Cannot read field "id" because the return value of "org.robovm.idea.running.RoboVmIOSRunConfigurationSettingsEditor$Decorator.from(javax.swing.JComboBox)" is null
=> * fixed: #778 -- Idea run dialog was not saving Sim details if no device is attached and selected in preferred device udid

build.sh, plugins/gradle/build.gradle, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractSimulatorTask.java
it discovered a set of issue:
```
Execution failed for task ':validatePlugins'.
> Plugin validation failed with 1 problem:
- Error: Type 'org.robovm.gradle.tasks.AbstractSimulatorTask' method 'getDeviceType()' should not be annotated with: @Internal.
```
fix: annotation was removed (method doesn't look as pure getter) and `validatePlugins` option was added to build invocation
```
* What went wrong:
A problem occurred configuring project ':facebook-share-kit'.
> Could not create task ':facebook-share-kit:launchIPhoneSimulator'.
> Could not create task of type 'IPhoneSimulatorTask'.
> Could not generate a decorated class for type IPhoneSimulatorTask.
> org/robovm/compiler/log/Logger
Caused by: java.lang.NoClassDefFoundError: org/robovm/compiler/log/Logger
```
root case of it: …
=> * fixed: gradle plugin failed to be deployed

plugins/idea/src/main/java/org/robovm/idea/sdk/RoboVmSdkType.java
We use several components with Idea plugin that were marked deprecated for several years already. And seems in recent IDEA version 2024.1.1 we have an issue with RoboVM SDK being added and then removed. (check video)
As workaround while code is not migrated SDK should be added manually. But it wasn't working as well. This PR fixed it, 
https://github.com/MobiVM/robovm/assets/24827357/41b6102c-47c1-4bd9-ab49-95c506625580
- It was failing due version was not returned
- SDK paths were configured not on Writable scope
=> * idea: fixed -- manual adding of RoboVM SDK from File/Project structure

compiler/objc/src/main/java/org/robovm/objc/ObjCClass.java, compiler/objc/src/main/java/org/robovm/objc/ObjCObject.java
reported over gitter, in scope of CleverAds:
```
"Terminating app due to uncaught exception 'org.robovm.objc.ObjCClassNotFoundException', reason: 'org.robovm.objc.ObjCClassNotFoundException: Could not find Java class corresponding to Objective-C class: CleverAdsSolutions.ImpressionWrapper".
```
Then trying to marshal pointer to Java world and turn it into Interface instance ObjC runtime tries find as much complete as possible class instance representation from this pointer to allow to have not just as $ObjCProxy of this interface/protocol but a proper class instance.
In case of reported issue:
there was expected `CASStatusHandler` protocol in callback. CAS provided pure Swift class `CleverAdsSolutions.ImpressionWrapper` that implemented it. This class is extended from `Swift._SwiftObject` …
=> * fixed: ObjCClassNotFoundException when marshaling protocols implemented in pure Swift classes

compiler/rt/libcore/crypto/src/main/java/org/conscrypt/ClientSessionContext.java
making multiple request to same host/port cause some of them terminated with message
> error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (/Users/tomski/Coding/asidik/robovm/target/checkout/compiler/vm/rt/android/external/openssl/ssl/s23_clnt.c:714 0x107f58871:0x00000000)
(or application crashed random places)
Reusing same Session cause same native SSL_Session to be used with each opened OpenSSLSocketImpl. It associates it's native pointer with its SSL.
```
sessionToReuse = this.getCachedClientSession(clientSessionContext);
if (sessionToReuse != null) {
NativeCrypto.SSL_set_session(this.sslNativePointer, sessionToReuse.sslSessionNativePointer);
}
```
As result multiple OpenSSLSocketImpl and its SSL will use same single session. Problem appear once this socked is being …
=> * SSL session caching/reusing disabled to prevent memory corruption

compiler/rt/libcore/luni/src/main/java/java/lang/Double.java, compiler/rt/libcore/luni/src/main/java/java/lang/Float.java, compiler/rt/libcore/luni/src/main/java/java/lang/Integer.java, compiler/rt/libcore/luni/src/main/java/java/lang/Long.java, compiler/rt/libcore/luni/src/main/java/java/lang/Short.java
It seems recent Kotlin versions are generating code that relies on the Java 1.8 static `hashCode(x)` functions which are not present in the libcore implementation, which results in "method not found" errors e.g. when using a data class with double members in a hashed collection.
This PR adds those functions for Double, Float, Long, Integer and Short.
=> Implement static hashcode functions for scalar types

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/ProvisioningProfile.java, compiler/llvm/src/test/java/org/robovm/llvm/ObjectFileTest.java, compiler/vm/CMakeLists.txt, plugins/gradle/README.md, plugins/gradle/src/main/java/org/robovm/gradle/RoboVMPluginExtension.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java, plugins/maven/plugin/src/main/java/org/robovm/maven/plugin/AbstractRoboVMMojo.java
- bitcode is disabled as deprecated, causes binary verification fail at apple side, also causes VM natives compilation to fail
- added `Library/Developer/Xcode/UserData/Provisioning Profiles` folder for provisioning profiles
- fixed ObjectFileTest. Recent clang includes dwarf v5 debug info and it is not compatible with our implementation (affects only test)
- CMAKE -- fixed warning that `exec_program should not be used`
=> * maintenance: XCode16 support (also fixes #795)

compiler/compiler/src/main/java/org/robovm/compiler/target/ios/SimLauncherProcess.java
fixed #798
Code to reproduce:
```
StringBuilder sb = new StringBuilder();
for (int i = 0; i < 16384; i++)
sb.append('c');
System.out.println(sb);
```
=> * simctl launch: switched to `--console-pty` to workaround 16Kb PIPE buffer limitation on MacOSx

plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractSimulatorTask.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/ConsoleTask.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/IOSDeviceTask.java
These changes allows to pass arguments to application, when launching it on device/simulator similar to arguments field in Idea run/debug configuration. Beside debug/specific cases this is also required to enable debug mode of Crashlytics: https://firebase.google.com/docs/crashlytics/test-implementation?platform=ios
Custom commands are supported since Gradle v5.
Usage as simple as: `./gradlew  launchIPhoneSimulator --info --args "'hello world'"`
String passed in `--args` is then tokenized into individual arguments, e.g. `--args="one two"` will produce two arguments in args array ["one", "two"], if spaces to be considered as part of argument, quotation to be used.
Gradle also propagate option description to help command:
```
./gradlew help --task launchIPhoneSimulator
> Task :help
Detailed …
```
=> * gradle plugin: arguments support for launch* tasks

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, compiler/compiler/src/main/java/org/robovm/compiler/config/tools/IBXOptions.java, compiler/compiler/src/main/java/org/robovm/compiler/config/tools/Tools.java, compiler/compiler/src/main/java/org/robovm/compiler/target/ios/IOSTarget.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/IBXcodeProject.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/export/FrameworkExportData.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/export/XCodeProjectExporter.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/pbxproj/PBXFile.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/pbxproj/PBXGroup.java, plugins/ibxcode/src/main/java/org/robovm/ibxcode/pbxproj/PBXProject.java, plugins/idea/src/main/java/org/robovm/idea/ibxcode/RoboVmIbXcodeProjectTask.java, plugins/idea/src/main/resources/META-INF/plugin.xml
Main reason -- to be able to compile Stub in Xcode without errors.
What was fixed:
Info.plist is now generated and included into xcode project.
Stub `int main() {}` is now generated and included into xcode project.
Error while compiling pre-compiled header file where all framework are being referenced. XCode doesn't seem to recognise single arch framework. Changes where done:
- propagate XCFrameworks instead of its framework.
- clang modules are enabled now;
- not all frameworks have umbrella header with same name, e.g. `FrameworkName/FrameworkName.h`, logic added to look for Swift umbrellas as well.
- if umbrella header is not found -- framework is not included into pre-compiled headers.
To have manual control over the logic and to be able to add extra imports and filter out not required …
=> * maintenance: interface builder integration

compiler/compiler/src/main/java/org/robovm/compiler/config/Config.java, plugins/gradle/src/main/java/org/robovm/gradle/tasks/AbstractRoboVMTask.java
It allows to specify/override properties that are used in property file, as long as Info.plist etc
Usage:
```
./gradlew help launchIPhoneSimulator --info  -Papp.name=test
```
=> * gradle plugin: propagating gradle properties to config.properties

plugins/idea/src/main/java/org/robovm/idea/compilation/RoboVmCompileTask.java
(otherwise, runtime dependencies are not included into the build)
=> * fixed: [Idea plugin] RoboVM should compile with Runtime class path 
